/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["index"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/authentication": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Authenticate user */
    post: operations["login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/authentication/test": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Test access token */
    get: operations["testAuth"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/blogs/publish/latest": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["sendLatestBlogPost"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/blogs/publish/latest/email": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["sendLatestBlogPostEmail"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/blogs/publish/latest/push": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["sendLatestBlogPostPush"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/blogs/publish/latest/telegram": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["sendLatestBlogPostTelegram"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/blogs/publish/latest/whatsapp": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["sendLatestBlogPostWhatsApp"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/bulletins": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @deprecated */
    get: operations["getPublishedJSONBulletins0"];
    /** Create bulletin */
    put: operations["createJSONBulletin"];
    /** Create bulletins */
    post: operations["createJSONBulletins"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/bulletins/caaml": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get published bulletins for date as CAAML XML */
    get: operations["getPublishedCaamlBulletins"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/bulletins/caaml/json": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get published bulletins for date as CAAML JSON */
    get: operations["getPublishedCaamlJsonBulletins"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/bulletins/change": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Change bulletins */
    post: operations["changeBulletins"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/bulletins/check": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Check bulletins */
    get: operations["checkBulletins"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/bulletins/edit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get bulletins for date */
    get: operations["getJSONBulletins"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/bulletins/edit/caaml/json": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get bulletins for date as CAAML JSON */
    get: operations["getCaamlJsonBulletins"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/bulletins/highest": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get highest danger rating */
    get: operations["getHighestDangerRating"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/bulletins/json": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get published bulletins for date */
    get: operations["getPublishedJSONBulletins"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/bulletins/latest": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get latest bulletin date */
    get: operations["getLatest"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/bulletins/pdf": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get published bulletins as PDF */
    get: operations["getPublishedBulletinsAsPDF"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/bulletins/preview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Get bulletin preview as PDF */
    post: operations["getPreviewPdf"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/bulletins/publish": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Publish a major update to an already published bulletin (not at 5PM nor 8AM).
     * @description Publish a major update to an already published bulletin (not at 5PM nor 8AM).
     */
    post: operations["publishBulletins"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/bulletins/publish/all": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Publish a major update to an already published bulletin (not at 5PM nor 8AM).
     * @description Publish a major update to an already published bulletin (not at 5PM nor 8AM).
     */
    post: operations["publishAllBulletins"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/bulletins/publish/email": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["sendEmail"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/bulletins/publish/push": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["triggerPushNotifications"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/bulletins/publish/telegram": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["triggerTelegramChannel"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/bulletins/publish/whatsapp": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["triggerWhatsAppChannel"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/bulletins/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getStatus"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/bulletins/status/internal": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getInternalStatus"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/bulletins/status/publication": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getPublicationStatus"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/bulletins/status/publications": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getPublicationsStatus"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/bulletins/submit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Submit bulletins */
    post: operations["submitBulletins"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/bulletins/{bulletinId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get bulletin by ID */
    get: operations["getJSONBulletin"];
    put?: never;
    /** Update bulletin */
    post: operations["updateJSONBulletin"];
    /** Delete bulletin */
    delete: operations["deleteJSONBulletin"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/danger-sources": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get danger sources for season */
    get: operations["getDangerSources"];
    put?: never;
    /** Create or update danger source */
    post: operations["saveDangerSource"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/danger-sources/edit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get danger source variants for date */
    get: operations["getVariants"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/danger-sources/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getInternalStatus_1"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/danger-sources/variants": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Save danger source variant (create/insert or update) */
    post: operations["saveDangerSourceVariant"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/danger-sources/variants/replace": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Replace variants (save and delete obsolete) */
    post: operations["replaceVariants"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/danger-sources/variants/{variantId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get variant by ID */
    get: operations["getVariantById"];
    put?: never;
    post?: never;
    /** Delete danger source variant */
    delete: operations["deleteVariant"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/danger-sources/{dangerSourceId}/edit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get danger source variants for danger source and date */
    get: operations["getVariantsForDangerSource"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/email/subscribe": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Subscribe email notification */
    post: operations["addSubscriber"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/media": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Save media file */
    post: operations["saveMediaFile"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/media/rss": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get media files as RSS feed */
    get: operations["getRssFeed"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/openapi.json": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getOpenApiJson"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/openapi.yml": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getOpenApi"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/push/key": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get VAPID public key */
    get: operations["key"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/push/subscribe": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Subscribe push notification */
    post: operations["subscribe"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/push/unsubscribe": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Unsubscribe push notification */
    post: operations["unsubscribe"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/regions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all regions */
    get: operations["getRegions"];
    put?: never;
    /** Create or update region */
    post: operations["saveRegion"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/regions/region": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get region for ID */
    get: operations["getRegion"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/server": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get local server configuration */
    get: operations["getLocalServerConfiguration"];
    put?: never;
    /** Create or update server configuration */
    post: operations["saveServerConfiguration"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/server/external": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get external server configurations */
    get: operations["getExternalServerConfigurations"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/server/info": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get server version info */
    get: operations["getServerVersionInfo"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/statistics": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get bulletin statistics */
    get: operations["getBulletinCsv"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/statistics/danger-sources": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get danger source statistics */
    get: operations["getDangerSourceCsv"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/statistics/vr": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Save VR statistics */
    post: operations["saveMediaFile_1"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/status/channels": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get status of publication channels that are associated with the current user's regions */
    get: operations["getStatus_1"];
    put?: never;
    /** Trigger status checks for all publication channels that are associated with the current user's regions */
    post: operations["triggerStatusChecks"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/user": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all users */
    get: operations["getUsers"];
    put?: never;
    /** Create or update user */
    post: operations["saveUser"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/user/change": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Change password */
    put: operations["changePassword"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/user/check": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Check password */
    put: operations["checkPassword"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/user/regions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all regions */
    get: operations["getRegions_1"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/user/roles": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all roles */
    get: operations["getRoles"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/user/stress-level": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List stress level entries of user */
    get: operations["getStressLevels"];
    put?: never;
    /** Create stress level entry */
    post: operations["postStressLevel"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/user/stress-level/team": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List stress level entries of team */
    get: operations["getTeamStressLevels"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/user/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete user */
    delete: operations["deleteUser"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/user/{id}/reset": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Reset user password */
    put: operations["resetPassword"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AbstractPersistentObject: {
      id?: string | null;
    };
    /** @enum {string} */
    ArtificialAvalancheReleaseProbability: "one" | "two" | "three" | "four";
    /** @enum {string} */
    Aspect: "N" | "NE" | "E" | "SE" | "S" | "SW" | "W" | "NW";
    "AuthenticationService.AuthenticationResponse": {
      user: components["schemas"]["User"];
      regions: components["schemas"]["Region"][];
      access_token: string;
    };
    "AuthenticationService.Credentials": {
      username: string;
      password: string;
    };
    "AuthenticationService.Username": {
      username: string;
    };
    /** @description This class holds all information about one avalanche bulletin. */
    AvalancheBulletin: components["schemas"]["AbstractPersistentObject"] & {
      id?: string | null;
      /** @description Information about the author of the avalanche bulletin */
      author?: components["schemas"]["User"] | null;
      additionalAuthors?: string[];
      /** Format: date-time */
      saveDate?: string;
      ownerRegion?: string;
      highlightsTextcat?: string;
      avActivityHighlightsTextcat?: string;
      avActivityCommentTextcat?: string;
      snowpackStructureHighlightsTextcat?: string;
      snowpackStructureCommentTextcat?: string;
      tendencyCommentTextcat?: string;
      generalHeadlineCommentTextcat?: string;
      synopsisCommentTextcat?: string;
      avActivityHighlightsNotes?: string;
      avActivityCommentNotes?: string;
      snowpackStructureHighlightsNotes?: string;
      snowpackStructureCommentNotes?: string;
      tendencyCommentNotes?: string;
      generalHeadlineCommentNotes?: string;
      highlights?: components["schemas"]["Texts"];
      avActivityHighlights?: components["schemas"]["Texts"];
      avActivityComment?: components["schemas"]["Texts"];
      synopsisHighlights?: components["schemas"]["Texts"];
      synopsisComment?: components["schemas"]["Texts"];
      snowpackStructureHighlights?: components["schemas"]["Texts"];
      snowpackStructureComment?: components["schemas"]["Texts"];
      travelAdvisoryHighlights?: components["schemas"]["Texts"];
      travelAdvisoryComment?: components["schemas"]["Texts"];
      tendencyComment?: components["schemas"]["Texts"];
      generalHeadlineComment?: components["schemas"]["Texts"];
      tendency?: components["schemas"]["Tendency"];
      dangerPattern1?: components["schemas"]["DangerPattern"];
      dangerPattern2?: components["schemas"]["DangerPattern"];
      /** Format: date-time */
      publicationDate?: string;
      validity?: components["schemas"]["AvalancheBulletin.Validity"];
      /** @description The recommended regions the avalanche bulletin is for. */
      suggestedRegions?: string[];
      /** @description The saved regions the avalanche bulletin is for. */
      savedRegions?: string[];
      regions?: string[];
      /** @description The published regions the avalanche bulletin is for. */
      publishedRegions?: string[];
      strategicMindset?: components["schemas"]["StrategicMindset"];
      forenoon?: components["schemas"]["AvalancheBulletinDaytimeDescription"] | null;
      afternoon?: components["schemas"]["AvalancheBulletinDaytimeDescription"] | null;
      hasDaytimeDependency?: boolean;
    };
    "AvalancheBulletin.Validity": {
      /** Format: date-time */
      from?: string;
      /** Format: date-time */
      until?: string;
    };
    AvalancheBulletinDaytimeDescription: components["schemas"]["AbstractPersistentObject"] & {
      id?: string | null;
      warningLevelId?: string;
      hasElevationDependency?: boolean;
      /** Format: int32 */
      elevation?: number;
      treeline?: boolean;
      dangerRatingAbove?: components["schemas"]["DangerRating"];
      terrainFeatureAboveTextcat?: string;
      terrainFeatureAbove?: components["schemas"]["Text"][];
      dangerRatingBelow?: components["schemas"]["DangerRating"];
      terrainFeatureBelowTextcat?: string;
      terrainFeatureBelow?: components["schemas"]["Text"][];
      complexity?: components["schemas"]["Complexity"];
      avalancheProblem1?: components["schemas"]["AvalancheProblem"] | null;
      avalancheProblem2?: components["schemas"]["AvalancheProblem"] | null;
      avalancheProblem3?: components["schemas"]["AvalancheProblem"] | null;
      avalancheProblem4?: components["schemas"]["AvalancheProblem"] | null;
      avalancheProblem5?: components["schemas"]["AvalancheProblem"] | null;
    };
    "AvalancheBulletinService.Highest": {
      dangerRating: components["schemas"]["DangerRating"];
    };
    "AvalancheBulletinService.LatestBulletin": {
      /** Format: date-time */
      date: string;
    };
    "AvalancheBulletinStatusService.Status": {
      /** Format: date-time */
      date: string;
      status: components["schemas"]["BulletinStatus"];
      report: components["schemas"]["AvalancheReport"];
    };
    AvalancheProblem: components["schemas"]["AbstractPersistentObject"] & {
      id?: string | null;
      avalancheType?: components["schemas"]["AvalancheType"];
      avalancheProblem?: components["schemas"]["AvalancheProblem_1"];
      aspects?: components["schemas"]["Aspect"][];
      /** Format: int32 */
      elevationHigh?: number;
      treelineHigh?: boolean;
      /** Format: int32 */
      elevationLow?: number;
      treelineLow?: boolean;
      dangerRatingDirection?: components["schemas"]["Direction"];
      /** @description Information about the selected field in the EAWS matrix */
      matrixInformation?: components["schemas"]["MatrixInformation"];
      /** @description Information about the selected field in the EAWS matrix */
      eawsMatrixInformation?: components["schemas"]["EawsMatrixInformation"];
      terrainFeatureTextcat?: string;
      terrainFeature?: components["schemas"]["Text"][];
    };
    /** @enum {string} */
    AvalancheProblem_1:
      | "new_snow"
      | "wind_slab"
      | "persistent_weak_layers"
      | "wet_snow"
      | "gliding_snow"
      | "favourable_situation"
      | "cornices"
      | "no_distinct_avalanche_problem";
    /** @description This class holds all information about one avalanche report. */
    AvalancheReport: components["schemas"]["AbstractPersistentObject"] & {
      id?: string | null;
      bulletins?: components["schemas"]["AvalancheBulletin"][];
      region?: components["schemas"]["Region"] | null;
      /** Format: date-time */
      date?: string;
      /** Format: date-time */
      timestamp?: string;
      status?: components["schemas"]["BulletinStatus"];
      caamlV5Created?: boolean;
      caamlV6Created?: boolean;
      jsonCreated?: boolean;
      pdfCreated?: boolean;
      htmlCreated?: boolean;
      mapCreated?: boolean;
      emailCreated?: boolean;
      telegramSent?: boolean;
      whatsAppSent?: boolean;
      pushSent?: boolean;
      mediaFileUploaded?: boolean;
      globalBulletins?: components["schemas"]["AvalancheBulletin"][];
      serverInstance?: components["schemas"]["LocalServerInstance"];
    };
    /** @enum {string} */
    AvalancheSize: "small" | "medium" | "large" | "very_large" | "extreme";
    /** @enum {string} */
    AvalancheType: "slab" | "loose" | "glide";
    /** @enum {string} */
    BulletinStatus: "republished" | "resubmitted" | "updated" | "published" | "submitted" | "draft" | "missing";
    /**
     * @description The version of CAAML (Canadian Avalanche Association Markup Language)
     * @enum {string}
     */
    CaamlVersion: "V5" | "V6" | "V6_JSON";
    /** @enum {string} */
    Characteristic: "low" | "medium" | "high" | "very_high";
    /** @enum {string} */
    Complexity: "easy" | "challenging" | "complex";
    /** @enum {string} */
    CreationProcess:
      | "radiation_recrystallization"
      | "diurnal_recrystallization"
      | "melt_layer_recrystallization"
      | "surface_hoar_formation";
    /** @enum {string} */
    Crust: "no" | "partly" | "yes";
    /** @enum {string} */
    DangerPattern: "dp1" | "dp2" | "dp3" | "dp4" | "dp5" | "dp6" | "dp7" | "dp8" | "dp9" | "dp10";
    /** @enum {string} */
    DangerRating: "missing" | "no_snow" | "no_rating" | "low" | "moderate" | "considerable" | "high" | "very_high";
    /** @enum {string} */
    DangerRatingModificator: "minus" | "equal" | "plus";
    /** @enum {string} */
    DangerSign: "shooting_cracks" | "whumpfing" | "fresh_avalanches" | "glide_cracks";
    /** @description This class holds all information about one danger source. */
    DangerSource: components["schemas"]["AbstractPersistentObject"] & {
      id?: string | null;
      ownerRegion?: string;
      /** Format: date-time */
      creationDate?: string;
      title?: string;
      description?: string;
    };
    /** @description This class holds all information about one danger source variant. */
    DangerSourceVariant: components["schemas"]["AbstractPersistentObject"] & {
      id?: string | null;
      originalDangerSourceVariantId?: string;
      forecastDangerSourceVariantId?: string;
      dangerSource?: components["schemas"]["DangerSource"] | null;
      title?: string;
      /** Format: date-time */
      creationDate?: string;
      /** Format: date-time */
      updateDate?: string;
      /**
       * Format: date-time
       * @description Validity of the danger source variant.
       */
      validFrom?: string;
      /** Format: date-time */
      validUntil?: string;
      dangerSourceVariantStatus?: components["schemas"]["DangerSourceVariantStatus"];
      dangerSourceVariantType?: components["schemas"]["DangerSourceVariantType"];
      ownerRegion?: string;
      /** @description The regions where the danger source variant is present. */
      regions?: string[];
      hasDaytimeDependency?: boolean;
      avalancheType?: components["schemas"]["AvalancheType"];
      aspects?: components["schemas"]["Aspect"][];
      /** Format: int32 */
      elevationHigh?: number;
      treelineHigh?: boolean;
      /** Format: int32 */
      elevationLow?: number;
      treelineLow?: boolean;
      aspectsOfExistence?: components["schemas"]["Aspect"][];
      /** Format: int32 */
      elevationHighOfExistence?: number;
      treelineHighOfExistence?: boolean;
      /** Format: int32 */
      elevationLowOfExistence?: number;
      treelineLowOfExistence?: boolean;
      dangerIncreaseWithElevation?: boolean;
      highestDangerAspect?: components["schemas"]["Aspect"];
      dangerPeak?: components["schemas"]["Daytime"];
      slopeGradient?: components["schemas"]["SlopeGradient"];
      runoutIntoGreen?: boolean;
      penetrateDeepLayers?: boolean;
      naturalRelease?: components["schemas"]["Probability"];
      dangerSigns?: components["schemas"]["DangerSign"][];
      /** @description Information about the selected field in the EAWS matrix */
      eawsMatrixInformation?: components["schemas"]["EawsMatrixInformation"];
      comment?: string;
      textcat?: string;
      uncertainty?: string;
      /** @description --------------------- */
      glidingSnowActivity?: components["schemas"]["GlidingSnowActivity"];
      /** Format: int32 */
      glidingSnowActivityValue?: number;
      /** Format: int32 */
      snowHeightUpperLimit?: number;
      /** Format: int32 */
      snowHeightLowerLimit?: number;
      /** Format: int32 */
      snowHeightAverage?: number;
      zeroDegreeIsotherm?: boolean;
      /** @description --------------- */
      slabGrainShape?: components["schemas"]["GrainShape"];
      /** Format: int32 */
      slabThicknessUpperLimit?: number;
      /** Format: int32 */
      slabThicknessLowerLimit?: number;
      slabHandHardnessUpperLimit?: components["schemas"]["HandHardness"];
      slabHandHardnessLowerLimit?: components["schemas"]["HandHardness"];
      slabHardnessProfile?: components["schemas"]["Tendency"];
      slabEnergyTransferPotential?: components["schemas"]["Characteristic"];
      slabDistribution?: components["schemas"]["Distribution"];
      weakLayerGrainShapes?: components["schemas"]["GrainShape"][];
      /** Format: double */
      weakLayerGrainSizeUpperLimit?: number;
      /** Format: double */
      weakLayerGrainSizeLowerLimit?: number;
      weakLayerPersistent?: boolean;
      weakLayerThickness?: components["schemas"]["Thickness"];
      weakLayerStrength?: components["schemas"]["Characteristic"];
      weakLayerWet?: boolean;
      weakLayerCrustAbove?: components["schemas"]["Crust"];
      weakLayerCrustBelow?: components["schemas"]["Crust"];
      weakLayerPosition?: components["schemas"]["SnowpackPosition"];
      weakLayerCreation?: components["schemas"]["CreationProcess"];
      weakLayerDistribution?: components["schemas"]["Distribution"];
      dangerSpotRecognizability?: components["schemas"]["Recognizability"];
      remoteTriggering?: components["schemas"]["Probability"];
      terrainTypes?: components["schemas"]["TerrainType"][];
      /** @description --------------------- */
      looseSnowGrainShape?: components["schemas"]["GrainShape"];
      looseSnowMoisture?: components["schemas"]["Wetness"];
    };
    /** @enum {string} */
    DangerSourceVariantStatus: "active" | "dormant" | "inactive";
    /** @enum {string} */
    DangerSourceVariantType: "forecast" | "analysis";
    DangerSourceVariantsStatus: {
      /** Format: date-time */
      date: string;
      forecast: boolean;
      analysis: boolean;
    };
    /** @enum {string} */
    Daytime: "evening" | "first_night_half" | "second_night_half" | "morning" | "forenoon" | "afternoon";
    /** @enum {string} */
    Direction: "up" | "down";
    /** @enum {string} */
    Distribution: "isolated" | "specific" | "widespread";
    EawsMatrixInformation: {
      dangerRating?: components["schemas"]["DangerRating"];
      dangerRatingModificator?: components["schemas"]["DangerRatingModificator"];
      avalancheSize?: components["schemas"]["AvalancheSize"];
      snowpackStability?: components["schemas"]["SnowpackStability"];
      frequency?: components["schemas"]["Frequency"];
      /** Format: int32 */
      avalancheSizeValue?: number;
      /** Format: int32 */
      snowpackStabilityValue?: number;
      /** Format: int32 */
      frequencyValue?: number;
    };
    /** @enum {string} */
    Frequency: "none" | "few" | "some" | "many";
    /** @enum {string} */
    GlidingSnowActivity: "low" | "medium" | "high";
    /** @enum {string} */
    GrainShape:
      | "PP"
      | "MM"
      | "DF"
      | "RG"
      | "FC"
      | "DH"
      | "SH"
      | "MF"
      | "IF"
      | "PPco"
      | "PPnd"
      | "PPpl"
      | "PPsd"
      | "PPir"
      | "PPgp"
      | "PPhl"
      | "PPip"
      | "PPrm"
      | "MMrp"
      | "MMci"
      | "DFdc"
      | "DFbk"
      | "RGsr"
      | "RGlr"
      | "RGwp"
      | "RGxf"
      | "FCso"
      | "FCsf"
      | "FCxr"
      | "DHcp"
      | "DHpr"
      | "DHch"
      | "DHla"
      | "DHxr"
      | "SHsu"
      | "SHcv"
      | "SHxr"
      | "MFcl"
      | "MFpc"
      | "MFsl"
      | "MFcr"
      | "IFil"
      | "IFic"
      | "IFbi"
      | "IFrc"
      | "IFsc";
    /** @enum {string} */
    HandHardness: "fist" | "four_fingers" | "one_finger" | "pencil" | "knife" | "ice";
    /** @enum {string} */
    HazardSiteDistribution: "single" | "some" | "many" | "many_most" | "moderately_steep";
    /**
     * @description The enum contains the ISO 639-1 codes for available languages.
     * @enum {string}
     */
    LanguageCode: "de" | "it" | "en" | "fr" | "es" | "ca" | "oc";
    LocalServerInstance: {
      publishAt5PM: boolean;
      publishAt8AM: boolean;
      mapsPath: string;
      mapProductionUrl: string;
      pdfDirectory: string;
      htmlDirectory: string;
      mediaPath: string;
    };
    MatrixInformation: {
      artificialDangerRating?: components["schemas"]["DangerRating"];
      artificialAvalancheSize?: components["schemas"]["AvalancheSize"];
      artificialAvalancheReleaseProbability?: components["schemas"]["ArtificialAvalancheReleaseProbability"];
      artificialHazardSiteDistribution?: components["schemas"]["HazardSiteDistribution"];
      naturalDangerRating?: components["schemas"]["DangerRating"];
      naturalAvalancheReleaseProbability?: components["schemas"]["NaturalAvalancheReleaseProbability"];
      naturalHazardSiteDistribution?: components["schemas"]["HazardSiteDistribution"];
    };
    /** @enum {string} */
    NaturalAvalancheReleaseProbability: "one" | "two" | "three" | "four";
    /** @enum {string} */
    Position: "topleft" | "topright" | "bottomleft" | "bottomright";
    /** @enum {string} */
    Probability: "likely" | "possible" | "unlikely";
    PushSubscription: {
      /** Format: int64 */
      id?: number | null;
      /** Format: date-time */
      subscribeDate?: string;
      auth?: string;
      p256dh?: string;
      endpoint?: string;
      language?: components["schemas"]["LanguageCode"];
      region?: string;
      /** Format: int32 */
      failedCount?: number;
    };
    /** @enum {string} */
    Recognizability: "very_easy" | "easy" | "hard" | "very_hard";
    /** @description This class holds all information about one region. */
    Region: {
      id?: string;
      /** Format: int32 */
      microRegions?: number;
      subRegions?: string[];
      superRegions?: string[];
      neighborRegions?: string[];
      languageConfigurations?: components["schemas"]["RegionLanguageConfiguration"][];
      staticUrl?: string;
      enabledLanguages?: components["schemas"]["LanguageCode"][];
      ttsLanguages?: components["schemas"]["LanguageCode"][];
      publishBulletins?: boolean;
      publishBlogs?: boolean;
      createCaamlV5?: boolean;
      createCaamlV6?: boolean;
      createJson?: boolean;
      createMaps?: boolean;
      createPdf?: boolean;
      createSimpleHtml?: boolean;
      sendEmails?: boolean;
      sendTelegramMessages?: boolean;
      sendWhatsAppMessages?: boolean;
      sendPushNotifications?: boolean;
      enableMediaFile?: boolean;
      enableAvalancheProblemCornices?: boolean;
      enableAvalancheProblemNoDistinctAvalancheProblem?: boolean;
      showMatrix?: boolean;
      enableStrategicMindset?: boolean;
      enableStressLevel?: boolean;
      pdfColor?: string;
      emailColor?: string;
      /** Format: int32 */
      pdfMapYAmPm?: number;
      /** Format: int32 */
      pdfMapYFd?: number;
      /** Format: int32 */
      pdfMapWidthAmPm?: number;
      /** Format: int32 */
      pdfMapWidthFd?: number;
      /** Format: int32 */
      pdfMapHeight?: number;
      pdfFooterLogo?: boolean;
      pdfFooterLogoColorPath?: string;
      pdfFooterLogoBwPath?: string;
      simpleHtmlTemplateName?: string;
      geoDataDirectory?: string;
      mapLogoColorPath?: string;
      mapLogoBwPath?: string;
      mapLogoPosition?: components["schemas"]["Position"];
      imageColorbarColorPath?: string;
      imageColorbarBwPath?: string;
      enableDangerSources?: boolean;
      enableObservations?: boolean;
      enableModelling?: boolean;
      enabledEditableFields?: components["schemas"]["TextcatTextfield"][];
      enableWeatherTextField?: boolean;
      enableWeatherbox?: boolean;
      enableLineaExport?: boolean;
      defaultLang?: components["schemas"]["LanguageCode"];
      logoPath?: string;
      logoBwPath?: string;
      coatOfArms?: string;
      enableGeneralHeadline?: boolean;
      serverImagesUrl?: string;
    };
    RegionLanguageConfiguration: {
      lang?: components["schemas"]["LanguageCode"];
      websiteName?: string;
      warningServiceName?: string;
      warningServiceEmail?: string;
      url?: string;
      urlWithDate?: string;
    };
    /** @enum {string} */
    Role: "SUPERADMIN" | "ADMIN" | "FORECASTER" | "FOREMAN" | "OBSERVER";
    /** @description This class holds all information about a server instance. */
    ServerInstance: {
      /** Format: int64 */
      id?: number | null;
      name?: string;
      apiUrl?: string;
      userName?: string;
      password?: string;
      externalServer?: boolean;
    };
    "ServerInstanceService.ServerVersionInfo": {
      version: string;
    };
    /** @enum {string} */
    SlopeGradient: "moderately_steep" | "steep" | "very_steep" | "extremely_steep";
    /** @enum {string} */
    SnowpackPosition: "upper" | "middle" | "lower" | "ground";
    /** @enum {string} */
    SnowpackStability: "good" | "fair" | "poor" | "very_poor";
    StatusInformation: {
      ok: boolean;
      title: string;
      message: string;
    };
    /** @enum {string} */
    StrategicMindset:
      | "assessment"
      | "stepping_out"
      | "status_quo"
      | "stepping_back"
      | "entrenchment"
      | "free_ride"
      | "high_alert"
      | "spring_diurnal";
    StressLevel: {
      /** Format: date */
      date?: string;
      /** Format: int32 */
      stressLevel?: number;
      /** Format: date-time */
      lastUpdated?: string;
    };
    "SubscriptionService.EmailSubscription": {
      email: string;
      regions: string;
      language: components["schemas"]["LanguageCode"];
    };
    /** @enum {string} */
    Tendency: "decreasing" | "steady" | "increasing";
    /** @enum {string} */
    TerrainType:
      | "gullies_and_bowls"
      | "adjacent_to_ridgelines"
      | "distant_from_ridgelines"
      | "in_the_vicinity_of_peaks"
      | "pass_areas"
      | "shady_slopes"
      | "sunny_slopes"
      | "grassy_slopes"
      | "cut_slopes"
      | "wind_loaded_slopes"
      | "base_of_rock_walls"
      | "behind_abrupt_changes_in_the_terrain"
      | "transitions_into_gullies_and_bowls"
      | "areas_where_the_snow_cover_is_rather_shallow"
      | "transitions_from_a_shallow_to_a_deep_snowpack"
      | "highly_frequented_off_piste_terrain"
      | "little_used_backcountry_terrain"
      | "places_that_are_protected_from_the_wind"
      | "regions_exposed_to_the_foehn_wind"
      | "regions_with_a_lot_of_snow"
      | "regions_exposed_to_precipitation"
      | "regions_exposed_to_heavier_precipitation";
    Text: {
      languageCode?: components["schemas"]["LanguageCode"];
      text?: string;
    };
    /** @enum {string} */
    TextcatTextfield:
      | "avActivityComment"
      | "avActivityHighlights"
      | "generalHeadlineComment"
      | "highlights"
      | "snowpackStructureComment"
      | "snowpackStructureHighlights"
      | "synopsisComment"
      | "tendencyComment";
    Texts: components["schemas"]["AbstractPersistentObject"] & {
      id?: string | null;
      texts: components["schemas"]["Text"][];
    };
    /** @enum {string} */
    Thickness: "thick" | "thin";
    User: {
      /** @description Email address of the user */
      email?: string;
      /** @description Password of the user */
      password?: string;
      /** @description Name of the user */
      name?: string;
      roles?: components["schemas"]["Role"][];
      regions?: string[];
      /** @description Image of the user */
      image?: string;
      /** @description Organization the user works for */
      organization?: string;
      /** @description Preferred language of the user */
      languageCode?: components["schemas"]["LanguageCode"];
      deleted?: boolean;
    };
    "UserService.ChangePassword": {
      oldPassword: string;
      newPassword: string;
    };
    "UserService.CheckPassword": {
      password: string;
    };
    "UserService.ResetPassword": {
      newPassword: string;
    };
    /** @enum {string} */
    Wetness: "wet" | "moist" | "dry";
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  index: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description index 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/html": string;
        };
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AuthenticationService.Credentials"];
      };
    };
    responses: {
      /** @description login 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthenticationService.AuthenticationResponse"];
        };
      };
    };
  };
  testAuth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description testAuth 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthenticationService.Username"];
        };
      };
    };
  };
  sendLatestBlogPost: {
    parameters: {
      query: {
        region: string;
        lang: components["schemas"]["LanguageCode"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description sendLatestBlogPost 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  sendLatestBlogPostEmail: {
    parameters: {
      query: {
        region: string;
        lang: components["schemas"]["LanguageCode"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description sendLatestBlogPostEmail 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  sendLatestBlogPostPush: {
    parameters: {
      query: {
        region: string;
        lang: components["schemas"]["LanguageCode"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description sendLatestBlogPostPush 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  sendLatestBlogPostTelegram: {
    parameters: {
      query: {
        region: string;
        lang: components["schemas"]["LanguageCode"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description sendLatestBlogPostTelegram 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  sendLatestBlogPostWhatsApp: {
    parameters: {
      query: {
        region: string;
        lang: components["schemas"]["LanguageCode"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description sendLatestBlogPostWhatsApp 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getPublishedJSONBulletins0: {
    parameters: {
      query: {
        regions: string[];
        region: string;
        lang: components["schemas"]["LanguageCode"];
        version: components["schemas"]["CaamlVersion"];
        /** @description Date in the format yyyy-MM-dd'T'HH:mm:ssZZ */
        date: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description bulletins */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AvalancheBulletin"][];
          /** @example null */
          "application/xml": string;
        };
      };
    };
  };
  createJSONBulletin: {
    parameters: {
      query: {
        /** @description Date in the format yyyy-MM-dd'T'HH:mm:ssZZ */
        date: string;
        region: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AvalancheBulletin"];
      };
    };
    responses: {
      /** @description createJSONBulletin 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AvalancheBulletin"][];
        };
      };
    };
  };
  createJSONBulletins: {
    parameters: {
      query: {
        /** @description Date in the format yyyy-MM-dd'T'HH:mm:ssZZ */
        date: string;
        region: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AvalancheBulletin"][];
      };
    };
    responses: {
      /** @description createJSONBulletins 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AvalancheBulletin"][];
        };
      };
    };
  };
  getPublishedCaamlBulletins: {
    parameters: {
      query: {
        /** @description Date in the format yyyy-MM-dd'T'HH:mm:ssZZ */
        date: string;
        regions: string[];
        lang: components["schemas"]["LanguageCode"];
        version: components["schemas"]["CaamlVersion"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description getPublishedCaamlBulletins 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/xml": string;
        };
      };
    };
  };
  getPublishedCaamlJsonBulletins: {
    parameters: {
      query: {
        /** @description Date in the format yyyy-MM-dd'T'HH:mm:ssZZ */
        date: string;
        regions: string[];
        lang: components["schemas"]["LanguageCode"];
        version: components["schemas"]["CaamlVersion"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description getPublishedCaamlJsonBulletins 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string;
        };
      };
    };
  };
  changeBulletins: {
    parameters: {
      query: {
        /** @description Date in the format yyyy-MM-dd'T'HH:mm:ssZZ */
        date: string;
        region: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AvalancheBulletin"][];
      };
    };
    responses: {
      /** @description changeBulletins 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  checkBulletins: {
    parameters: {
      query: {
        region: string;
        /** @description Date in the format yyyy-MM-dd'T'HH:mm:ssZZ */
        date: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description checkBulletins 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string[];
        };
      };
    };
  };
  getJSONBulletins: {
    parameters: {
      query: {
        /** @description Date in the format yyyy-MM-dd'T'HH:mm:ssZZ */
        date: string;
        regions: string[];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description bulletins */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AvalancheBulletin"][];
        };
      };
    };
  };
  getCaamlJsonBulletins: {
    parameters: {
      query: {
        /** @description Date in the format yyyy-MM-dd'T'HH:mm:ssZZ */
        date: string;
        regions: string[];
        lang: components["schemas"]["LanguageCode"];
        version: components["schemas"]["CaamlVersion"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description getCaamlJsonBulletins 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string;
        };
      };
    };
  };
  getHighestDangerRating: {
    parameters: {
      query: {
        /** @description Date in the format yyyy-MM-dd'T'HH:mm:ssZZ */
        date: string;
        regions: string[];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description latest */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AvalancheBulletinService.Highest"];
        };
      };
    };
  };
  getPublishedJSONBulletins: {
    parameters: {
      query: {
        /** @description Date in the format yyyy-MM-dd'T'HH:mm:ssZZ */
        date: string;
        regions: string[];
        lang: components["schemas"]["LanguageCode"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description bulletins */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AvalancheBulletin"][];
        };
      };
    };
  };
  getLatest: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description getLatest 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AvalancheBulletinService.LatestBulletin"];
        };
      };
    };
  };
  getPublishedBulletinsAsPDF: {
    parameters: {
      query: {
        /** @description Date in the format yyyy-MM-dd'T'HH:mm:ssZZ */
        date: string;
        bulletinId?: string | null;
        microRegionId?: string | null;
        region: string;
        grayscale: boolean;
        lang: components["schemas"]["LanguageCode"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description getPublishedBulletinsAsPDF 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/pdf": string;
        };
      };
    };
  };
  getPreviewPdf: {
    parameters: {
      query: {
        region: string;
        lang: components["schemas"]["LanguageCode"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AvalancheBulletin"][];
      };
    };
    responses: {
      /** @description getPreviewPdf 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/pdf": string;
        };
      };
    };
  };
  publishBulletins: {
    parameters: {
      query: {
        region: string;
        /** @description Date in the format yyyy-MM-dd'T'HH:mm:ssZZ */
        date: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description publishBulletins 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  publishAllBulletins: {
    parameters: {
      query: {
        /** @description Date in the format yyyy-MM-dd'T'HH:mm:ssZZ */
        date: string;
        change: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description publishAllBulletins 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  sendEmail: {
    parameters: {
      query: {
        region: string;
        /** @description Date in the format yyyy-MM-dd'T'HH:mm:ssZZ */
        date: string;
        lang?: components["schemas"]["LanguageCode"] | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description sendEmail 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  triggerPushNotifications: {
    parameters: {
      query: {
        region: string;
        /** @description Date in the format yyyy-MM-dd'T'HH:mm:ssZZ */
        date: string;
        lang?: components["schemas"]["LanguageCode"] | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description triggerPushNotifications 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  triggerTelegramChannel: {
    parameters: {
      query: {
        region: string;
        /** @description Date in the format yyyy-MM-dd'T'HH:mm:ssZZ */
        date: string;
        lang?: components["schemas"]["LanguageCode"] | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description triggerTelegramChannel 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  triggerWhatsAppChannel: {
    parameters: {
      query: {
        region: string;
        /** @description Date in the format yyyy-MM-dd'T'HH:mm:ssZZ */
        date: string;
        lang?: components["schemas"]["LanguageCode"] | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description triggerWhatsAppChannel 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getStatus: {
    parameters: {
      query: {
        region: string;
        timezone: string;
        /** @description Date in the format yyyy-MM-dd'T'HH:mm:ssZZ */
        startDate: string;
        /** @description Date in the format yyyy-MM-dd'T'HH:mm:ssZZ */
        endDate: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description getStatus 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AvalancheBulletinStatusService.Status"][];
        };
      };
    };
  };
  getInternalStatus: {
    parameters: {
      query: {
        region: string;
        /** @description Date in the format yyyy-MM-dd'T'HH:mm:ssZZ */
        startDate: string;
        /** @description Date in the format yyyy-MM-dd'T'HH:mm:ssZZ */
        endDate: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description getInternalStatus 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AvalancheBulletinStatusService.Status"][];
        };
      };
    };
  };
  getPublicationStatus: {
    parameters: {
      query: {
        region: string;
        /** @description Date in the format yyyy-MM-dd'T'HH:mm:ssZZ */
        date: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description getPublicationStatus 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AvalancheBulletinStatusService.Status"];
        };
      };
    };
  };
  getPublicationsStatus: {
    parameters: {
      query: {
        region: string;
        /** @description Date in the format yyyy-MM-dd'T'HH:mm:ssZZ */
        startDate: string;
        /** @description Date in the format yyyy-MM-dd'T'HH:mm:ssZZ */
        endDate: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description getPublicationsStatus 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AvalancheBulletinStatusService.Status"][];
        };
      };
    };
  };
  submitBulletins: {
    parameters: {
      query: {
        region: string;
        /** @description Date in the format yyyy-MM-dd'T'HH:mm:ssZZ */
        date: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description submitBulletins 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getJSONBulletin: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        bulletinId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description bulletin */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AvalancheBulletin"];
        };
      };
    };
  };
  updateJSONBulletin: {
    parameters: {
      query: {
        /** @description Date in the format yyyy-MM-dd'T'HH:mm:ssZZ */
        date: string;
        region: string;
      };
      header?: never;
      path: {
        bulletinId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AvalancheBulletin"];
      };
    };
    responses: {
      /** @description updateJSONBulletin 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AvalancheBulletin"][];
        };
      };
    };
  };
  deleteJSONBulletin: {
    parameters: {
      query: {
        /** @description Date in the format yyyy-MM-dd'T'HH:mm:ssZZ */
        date: string;
        region: string;
      };
      header?: never;
      path: {
        bulletinId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description deleteJSONBulletin 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AvalancheBulletin"][];
        };
      };
    };
  };
  getDangerSources: {
    parameters: {
      query: {
        /** @description Date in the format yyyy-MM-dd'T'HH:mm:ssZZ */
        date: string;
        region: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description danger-sources */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DangerSource"][];
        };
      };
    };
  };
  saveDangerSource: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DangerSource"];
      };
    };
    responses: {
      /** @description saveDangerSource 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DangerSource"];
        };
      };
    };
  };
  getVariants: {
    parameters: {
      query: {
        /** @description Date in the format yyyy-MM-dd'T'HH:mm:ssZZ */
        date: string;
        region: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description danger-sources */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DangerSourceVariant"][];
        };
      };
    };
  };
  getInternalStatus_1: {
    parameters: {
      query: {
        region: string;
        /** @description Date in the format yyyy-MM-dd'T'HH:mm:ssZZ */
        startDate: string;
        /** @description Date in the format yyyy-MM-dd'T'HH:mm:ssZZ */
        endDate: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description getInternalStatus_1 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DangerSourceVariantsStatus"][];
        };
      };
    };
  };
  saveDangerSourceVariant: {
    parameters: {
      query: {
        /** @description Date in the format yyyy-MM-dd'T'HH:mm:ssZZ */
        date: string;
        region: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DangerSourceVariant"];
      };
    };
    responses: {
      /** @description saveDangerSourceVariant 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DangerSourceVariant"];
        };
      };
    };
  };
  replaceVariants: {
    parameters: {
      query: {
        /** @description Date in the format yyyy-MM-dd'T'HH:mm:ssZZ */
        date: string;
        region: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DangerSourceVariant"][];
      };
    };
    responses: {
      /** @description replaceVariants 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DangerSourceVariant"][];
        };
      };
    };
  };
  getVariantById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        variantId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description variant */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DangerSourceVariant"];
        };
      };
    };
  };
  deleteVariant: {
    parameters: {
      query: {
        /** @description Date in the format yyyy-MM-dd'T'HH:mm:ssZZ */
        date: string;
        region: string;
      };
      header?: never;
      path: {
        variantId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description deleteVariant 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DangerSourceVariant"][];
        };
      };
    };
  };
  getVariantsForDangerSource: {
    parameters: {
      query: {
        /** @description Date in the format yyyy-MM-dd'T'HH:mm:ssZZ */
        date: string;
        region: string;
      };
      header?: never;
      path: {
        dangerSourceId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description danger-sources */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DangerSourceVariant"][];
        };
      };
    };
  };
  addSubscriber: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SubscriptionService.EmailSubscription"];
      };
    };
    responses: {
      /** @description addSubscriber 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  saveMediaFile: {
    parameters: {
      query: {
        /** @description Date in the format yyyy-MM-dd'T'HH:mm:ssZZ */
        date: string;
        region: string;
        lang: components["schemas"]["LanguageCode"];
        important: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": {
          text?: string;
          /** Format: binary */
          file?: string;
        };
      };
    };
    responses: {
      /** @description saveMediaFile 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getRssFeed: {
    parameters: {
      query: {
        region: string;
        lang: components["schemas"]["LanguageCode"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description getRssFeed 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/rss+xml": string;
        };
      };
    };
  };
  getOpenApiJson: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description getOpenApiJson 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  getOpenApi: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description getOpenApi 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/x-yaml": string;
        };
      };
    };
  };
  key: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description key 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  subscribe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PushSubscription"];
      };
    };
    responses: {
      /** @description subscribe 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  unsubscribe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PushSubscription"];
      };
    };
    responses: {
      /** @description unsubscribe 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getRegions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description getRegions 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Region"][];
        };
      };
    };
  };
  saveRegion: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": string;
      };
    };
    responses: {
      /** @description saveRegion 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Region"];
        };
      };
    };
  };
  getRegion: {
    parameters: {
      query: {
        region: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description getRegion 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Region"];
        };
      };
    };
  };
  getLocalServerConfiguration: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description configuration */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LocalServerInstance"];
        };
      };
    };
  };
  saveServerConfiguration: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ServerInstance"];
      };
    };
    responses: {
      /** @description saveServerConfiguration 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServerInstance"];
        };
      };
    };
  };
  getExternalServerConfigurations: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description configuration */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServerInstance"][];
        };
      };
    };
  };
  getServerVersionInfo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description server version info */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServerInstanceService.ServerVersionInfo"];
        };
      };
    };
  };
  getBulletinCsv: {
    parameters: {
      query: {
        /** @description Date in the format yyyy-MM-dd'T'HH:mm:ssZZ */
        startDate: string;
        /** @description Date in the format yyyy-MM-dd'T'HH:mm:ssZZ */
        endDate: string;
        lang: components["schemas"]["LanguageCode"];
        extended: boolean;
        duplicate: boolean;
        regions: string[];
        obsoleteMatrix: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description getBulletinCsv 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/csv": string;
        };
      };
    };
  };
  getDangerSourceCsv: {
    parameters: {
      query: {
        /** @description Date in the format yyyy-MM-dd'T'HH:mm:ssZZ */
        startDate: string;
        /** @description Date in the format yyyy-MM-dd'T'HH:mm:ssZZ */
        endDate: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description getDangerSourceCsv 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/csv": string;
        };
      };
    };
  };
  saveMediaFile_1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** Format: binary */
          inputStream?: string;
        };
      };
    };
    responses: {
      /** @description saveMediaFile_1 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getStatus_1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description getStatus_1 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StatusInformation"][];
        };
      };
    };
  };
  triggerStatusChecks: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description triggerStatusChecks 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StatusInformation"][];
        };
      };
    };
  };
  getUsers: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description getUsers 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["User"][];
        };
      };
    };
  };
  saveUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["User"];
      };
    };
    responses: {
      /** @description saveUser 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
    };
  };
  changePassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserService.ChangePassword"];
      };
    };
    responses: {
      /** @description changePassword 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  checkPassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserService.CheckPassword"];
      };
    };
    responses: {
      /** @description checkPassword 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getRegions_1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description getRegions_1 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string[];
        };
      };
    };
  };
  getRoles: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description getRoles 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Role"];
        };
      };
    };
  };
  getStressLevels: {
    parameters: {
      query: {
        /** @description Date in the format yyyy-MM-dd'T'HH:mm:ssZZ */
        startDate: string;
        /** @description Date in the format yyyy-MM-dd'T'HH:mm:ssZZ */
        endDate: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description getStressLevels 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StressLevel"][];
        };
      };
    };
  };
  postStressLevel: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StressLevel"];
      };
    };
    responses: {
      /** @description postStressLevel 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StressLevel"];
        };
      };
    };
  };
  getTeamStressLevels: {
    parameters: {
      query: {
        region: string;
        /** @description Date in the format yyyy-MM-dd'T'HH:mm:ssZZ */
        startDate: string;
        /** @description Date in the format yyyy-MM-dd'T'HH:mm:ssZZ */
        endDate: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description getTeamStressLevels 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: components["schemas"]["StressLevel"][];
          };
        };
      };
    };
  };
  deleteUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description deleteUser 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  resetPassword: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserService.ResetPassword"];
      };
    };
    responses: {
      /** @description resetPassword 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
