import { z } from "zod/v4";

export const LanguageConfigurationSchema = z.object({
  lang: z.string().nullish().describe("Language code"),
  websiteName: z.string().nullish().describe("Website name"),
  warningServiceName: z.string().nullish().describe("Warning service name"),
  warningServiceEmail: z.email().nullish().describe("Warning service email"),
  url: z.url().nullish().describe("Website URL"),
  urlWithDate: z.url().nullish().describe("Website URL for date given by %s"),
});

export const RegionConfigurationSchema = z.object({
  id: z.string().nullish(),
  microRegions: z.coerce.number().nullish().describe("Number of micro regions"),
  subRegions: z.array(z.string()).nullish().describe("ID of sub regions"),
  superRegions: z.array(z.string()).nullish().describe("ID of super regions"),
  neighborRegions: z.array(z.string()).nullish().describe("ID ob neighbouring regions"),
  languageConfigurations: z.array(LanguageConfigurationSchema).nullish(),
  enabledLanguages: z.array(z.string()).nullish(),
  ttsLanguages: z.array(z.string()).nullish(),
  publishBulletins: z.boolean().nullish(),
  publishBlogs: z.boolean().nullish(),
  createCaamlV5: z.boolean().nullish(),
  createCaamlV6: z.boolean().nullish(),
  createJson: z.boolean().nullish(),
  createMaps: z.boolean().nullish(),
  createPdf: z.boolean().nullish(),
  sendEmails: z.boolean().nullish(),
  createSimpleHtml: z.boolean().nullish(),
  sendTelegramMessages: z.boolean().nullish(),
  sendWhatsAppMessages: z.boolean().nullish(),
  sendPushNotifications: z.boolean().nullish(),
  enableMediaFile: z.boolean().nullish(),
  enableAvalancheProblemCornices: z.boolean().nullish(),
  enableAvalancheProblemNoDistinctAvalancheProblem: z.boolean().nullish(),
  enableDangerSources: z.boolean().nullish(),
  enableObservations: z.boolean().nullish(),
  enableModelling: z.boolean().nullish(),
  enableWeatherbox: z.boolean().nullish(),
  enableStrategicMindset: z.boolean().nullish(),
  enableStressLevel: z.boolean().nullish(),
  enableEditableFields: z.boolean().nullish(),
  enableGeneralHeadline: z.boolean().nullish(),
  enableWeatherTextField: z.boolean().nullish(),
  showMatrix: z.boolean().nullish(),
  pdfColor: z.string().nullish(),
  emailColor: z.string().nullish(),
  pdfMapYAmPm: z.coerce.number().nullish(),
  pdfMapYFd: z.coerce.number().nullish(),
  pdfMapWidthAmPm: z.coerce.number().nullish(),
  pdfMapWidthFd: z.coerce.number().nullish(),
  pdfMapHeight: z.coerce.number().nullish(),
  pdfFooterLogo: z.boolean().nullish(),
  pdfFooterLogoColorPath: z.string().nullish(),
  pdfFooterLogoBwPath: z.string().nullish(),
  simpleHtmlTemplateName: z.string().nullish(),
  geoDataDirectory: z.string().nullish(),
  mapLogoColorPath: z.string().nullish(),
  mapLogoBwPath: z.string().nullish(),
  mapLogoPosition: z.string().nullish(),
  imageColorbarColorPath: z.string().nullish(),
  imageColorbarBwPath: z.string().nullish(),
  defaultLang: z.string().nullish(),
  logoPath: z.string().nullish(),
  logoBwPath: z.string().nullish(),
  coatOfArms: z.url().nullish().describe("Image URL for coat of arms"),
  staticUrl: z.url().nullish().describe("URL to static avalanche files"),
  $isNew: z.boolean().nullish(),
});

export type RegionConfiguration = z.infer<typeof RegionConfigurationSchema>;
