FROM mcr.microsoft.com/playwright:v1.58.2

ENV TZ="Europe/Vienna"

WORKDIR /home/

COPY package.json yarn.lock .yarnrc.yml playwright.config.ts .env ./
COPY .yarn .yarn
COPY local-types ./local-types

RUN corepack enable && yarn install --frozen-lockfile
