FROM mcr.microsoft.com/playwright:v1.61.1

ENV TZ="Europe/Vienna"

WORKDIR /home/

COPY package.json pnpm-lock.yaml playwright.config.ts .env ./
COPY local-types ./local-types

RUN corepack enable && pnpm install