FROM mcr.microsoft.com/playwright:v1.61.1

ENV TZ="Europe/Vienna"

WORKDIR /home/

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml playwright.config.ts .env .npmrc ./

RUN corepack enable && pnpm install