allowBuilds:
  "@parcel/watcher": false
  esbuild: false
  lmdb: false
  msgpackr-extract: false

patchedDependencies:
  leaflet: patches/leaflet.patch
  leaflet.sync: patches/leaflet.sync.patch

catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: 0.1.15
