// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}/albina/api` | `${string}://${string}/albina_dev/api` | (string & {});
};

export type AbstractPersistentObject = {
  id?: string | null;
};

export type ArtificialAvalancheReleaseProbability = "one" | "two" | "three" | "four";

export type Aspect = "N" | "NE" | "E" | "SE" | "S" | "SW" | "W" | "NW";

export type AuthenticationServiceAuthenticationResponse = {
  user: User;
  regions: Array<Region>;
  access_token: string;
};

export type AuthenticationServiceCredentials = {
  username: string;
  password: string;
};

export type AuthenticationServiceUsername = {
  username: string;
};

/**
 * This class holds all information about one avalanche bulletin.
 */
export type AvalancheBulletin = AbstractPersistentObject & {
  id?: string | null;
  /**
   * Information about the author of the avalanche bulletin
   */
  author?: User | null;
  additionalAuthors?: Array<string>;
  updateDate?: string;
  ownerRegion?: string;
  highlightsTextcat?: string;
  avActivityHighlightsTextcat?: string;
  avActivityCommentTextcat?: string;
  snowpackStructureHighlightsTextcat?: string;
  snowpackStructureCommentTextcat?: string;
  tendencyCommentTextcat?: string;
  generalHeadlineCommentTextcat?: string;
  synopsisCommentTextcat?: string;
  avActivityHighlightsNotes?: string;
  avActivityCommentNotes?: string;
  snowpackStructureHighlightsNotes?: string;
  snowpackStructureCommentNotes?: string;
  tendencyCommentNotes?: string;
  generalHeadlineCommentNotes?: string;
  highlights?: Array<AvalancheBulletinText>;
  avActivityHighlights?: Array<AvalancheBulletinText>;
  avActivityComment?: Array<AvalancheBulletinText>;
  synopsisHighlights?: Array<AvalancheBulletinText>;
  synopsisComment?: Array<AvalancheBulletinText>;
  snowpackStructureHighlights?: Array<AvalancheBulletinText>;
  snowpackStructureComment?: Array<AvalancheBulletinText>;
  travelAdvisoryHighlights?: Array<AvalancheBulletinText>;
  travelAdvisoryComment?: Array<AvalancheBulletinText>;
  tendencyComment?: Array<AvalancheBulletinText>;
  generalHeadlineComment?: Array<AvalancheBulletinText>;
  tendency?: Tendency;
  dangerPattern1?: DangerPattern;
  dangerPattern2?: DangerPattern;
  publicationDate?: string;
  validity?: AvalancheBulletinValidity;
  /**
   * The recommended regions the avalanche bulletin is for.
   */
  suggestedRegions?: Array<string>;
  /**
   * The saved regions the avalanche bulletin is for.
   */
  savedRegions?: Array<string>;
  savedOrPublishedRegions?: Array<string>;
  regions?: Array<string>;
  /**
   * The published regions the avalanche bulletin is for.
   */
  publishedRegions?: Array<string>;
  strategicMindset?: StrategicMindset;
  forenoon?: AvalancheBulletinDaytimeDescription | null;
  afternoon?: AvalancheBulletinDaytimeDescription | null;
  /**
   * Collection containing all photos of a bulletin
   */
  photos?: Array<AvalancheBulletinPhoto>;
  hasDaytimeDependency?: boolean;
};

export type AvalancheBulletinText = {
  languageCode: LanguageCode;
  text: string;
};

export type AvalancheBulletinValidity = {
  from?: string;
  until?: string;
};

export type AvalancheBulletinCustomDataBulletinPhoto = {
  url: string;
  copyright?: string;
  date?: string;
  microRegionId?: string;
  locationName?: string;
  latitude?: number;
  longitude?: number;
};

export type AvalancheBulletinDaytimeDescription = AbstractPersistentObject & {
  id?: string | null;
  warningLevelId?: string;
  hasElevationDependency?: boolean;
  elevation?: number;
  treeline?: boolean;
  dangerRatingAbove?: DangerRating;
  dangerRatingBelow?: DangerRating;
  complexity?: Complexity;
  avalancheProblem1?: AvalancheProblem | null;
  avalancheProblem2?: AvalancheProblem | null;
  avalancheProblem3?: AvalancheProblem | null;
  avalancheProblem4?: AvalancheProblem | null;
  avalancheProblem5?: AvalancheProblem | null;
};

export type AvalancheBulletinPhoto = AbstractPersistentObject & {
  id?: string | null;
  url?: string;
  copyright?: string;
  date?: string;
  microRegionId?: string;
  locationName?: string;
  latitude?: number;
  longitude?: number;
};

export type AvalancheBulletinServiceHighest = {
  dangerRating: DangerRating;
};

export type AvalancheBulletinServiceLatestBulletin = {
  date: string;
};

export type AvalancheBulletinStatusServiceStatus = {
  date: string;
  timestamp: string;
  status: BulletinStatus;
  isBeingPublished: boolean;
};

export type AvalancheProblem = AbstractPersistentObject & {
  id?: string | null;
  avalancheType?: AvalancheType;
  avalancheProblem?: AvalancheProblem1;
  aspects?: Array<Aspect>;
  elevationHigh?: number;
  treelineHigh?: boolean;
  elevationLow?: number;
  treelineLow?: boolean;
  dangerRatingDirection?: Direction;
  /**
   * Information about the selected field in the EAWS matrix
   */
  matrixInformation?: MatrixInformation;
  /**
   * Information about the selected field in the EAWS matrix
   */
  eawsMatrixInformation?: EawsMatrixInformation;
};

export type AvalancheProblem1 =
  | "new_snow"
  | "wind_slab"
  | "persistent_weak_layers"
  | "wet_snow"
  | "gliding_snow"
  | "favourable_situation"
  | "cornices"
  | "no_distinct_avalanche_problem";

export type AvalancheSize = "small" | "medium" | "large" | "very_large" | "extreme";

export type AvalancheType = "slab" | "loose" | "glide";

export type BlogItem = {
  id: string;
  title: string;
  content: string;
  published: string;
  categories: Array<string>;
  attachmentUrl: string;
};

export type BulletinStatus =
  | "republished"
  | "resubmitted"
  | "updated"
  | "published"
  | "submitted"
  | "draft"
  | "missing";

/**
 * The version of CAAML (Canadian Avalanche Association Markup Language)
 */
export type CaamlVersion = "V6" | "V6_JSON";

export type Characteristic = "low" | "medium" | "high" | "very_high";

export type ChecklistServiceChecklist = {
  checklistId: string;
  timestamp: string;
  checklistItems: Array<PublicationChecklistItem>;
  user: string;
};

export type Complexity = "easy" | "challenging" | "complex";

export type CreationProcess =
  | "radiation_recrystallization"
  | "diurnal_recrystallization"
  | "melt_layer_recrystallization"
  | "surface_hoar_formation";

export type Crust = "no" | "partly" | "yes";

export type DangerPattern = "dp1" | "dp2" | "dp3" | "dp4" | "dp5" | "dp6" | "dp7" | "dp8" | "dp9" | "dp10";

export type DangerRating =
  | "missing"
  | "no_snow"
  | "no_rating"
  | "low"
  | "moderate"
  | "considerable"
  | "high"
  | "very_high";

export type DangerRatingModificator = "none" | "minus" | "equal" | "plus";

export type DangerSign = "shooting_cracks" | "whumpfing" | "fresh_avalanches" | "glide_cracks";

/**
 * This class holds all information about one danger source.
 */
export type DangerSource = AbstractPersistentObject & {
  id?: string | null;
  ownerRegion?: string;
  creationDate?: string;
  title?: string;
  description?: string;
};

/**
 * This class holds all information about one danger source variant.
 */
export type DangerSourceVariant = AbstractPersistentObject & {
  id?: string | null;
  originalDangerSourceVariantId?: string;
  forecastDangerSourceVariantId?: string;
  dangerSource?: DangerSource | null;
  title?: string;
  creationDate?: string;
  updateDate?: string;
  /**
   * Validity of the danger source variant.
   */
  validFrom?: string;
  validUntil?: string;
  dangerSourceVariantStatus?: DangerSourceVariantStatus;
  dangerSourceVariantType?: DangerSourceVariantType;
  ownerRegion?: string;
  /**
   * The regions where the danger source variant is present.
   */
  regions?: Array<string>;
  hasDaytimeDependency?: boolean;
  avalancheType?: AvalancheType;
  aspects?: Array<Aspect>;
  elevationHigh?: number;
  treelineHigh?: boolean;
  elevationLow?: number;
  treelineLow?: boolean;
  aspectsOfExistence?: Array<Aspect>;
  elevationHighOfExistence?: number;
  treelineHighOfExistence?: boolean;
  elevationLowOfExistence?: number;
  treelineLowOfExistence?: boolean;
  dangerIncreaseWithElevation?: boolean;
  highestDangerAspect?: Aspect;
  dangerPeak?: Daytime;
  slopeGradient?: SlopeGradient;
  runoutIntoGreen?: boolean;
  penetrateDeepLayers?: boolean;
  naturalRelease?: Probability;
  dangerSigns?: Array<DangerSign>;
  /**
   * Information about the selected field in the EAWS matrix
   */
  eawsMatrixInformation?: EawsMatrixInformation;
  comment?: string;
  textcat?: string;
  uncertainty?: string;
  /**
   * ---------------------
   */
  glidingSnowActivity?: GlidingSnowActivity;
  glidingSnowActivityValue?: number;
  snowHeightUpperLimit?: number;
  snowHeightLowerLimit?: number;
  snowHeightAverage?: number;
  zeroDegreeIsotherm?: boolean;
  /**
   * ---------------
   */
  slabGrainShape?: GrainShape;
  slabThicknessUpperLimit?: number;
  slabThicknessLowerLimit?: number;
  slabHandHardnessUpperLimit?: HandHardness;
  slabHandHardnessLowerLimit?: HandHardness;
  slabHardnessProfile?: Tendency;
  slabEnergyTransferPotential?: Characteristic;
  slabDistribution?: Distribution;
  weakLayerGrainShapes?: Array<GrainShape>;
  weakLayerGrainSizeUpperLimit?: number;
  weakLayerGrainSizeLowerLimit?: number;
  weakLayerPersistent?: boolean;
  weakLayerThickness?: Thickness;
  weakLayerStrength?: Characteristic;
  weakLayerWet?: boolean;
  weakLayerCrustAbove?: Crust;
  weakLayerCrustBelow?: Crust;
  weakLayerPosition?: SnowpackPosition;
  weakLayerCreation?: CreationProcess;
  weakLayerDistribution?: Distribution;
  dangerSpotRecognizability?: Recognizability;
  remoteTriggering?: Probability;
  terrainTypes?: Array<TerrainType>;
  /**
   * ---------------------
   */
  looseSnowGrainShape?: GrainShape;
  looseSnowMoisture?: Wetness;
};

export type DangerSourceVariantStatus = "active" | "dormant" | "inactive";

export type DangerSourceVariantType = "forecast" | "analysis";

export type DangerSourceVariantsStatus = {
  date: string;
  forecast: boolean;
  analysis: boolean;
};

export type Daytime = "evening" | "first_night_half" | "second_night_half" | "morning" | "forenoon" | "afternoon";

export type Direction = "up" | "down";

export type Distribution = "isolated" | "specific" | "widespread";

export type EawsMatrixInformation = {
  dangerRating?: DangerRating;
  dangerRatingModificator?: DangerRatingModificator;
  avalancheSize?: AvalancheSize;
  snowpackStability?: SnowpackStability;
  frequency?: Frequency;
  avalancheSizeValue?: number;
  snowpackStabilityValue?: number;
  frequencyValue?: number;
};

export type Frequency = "none" | "few" | "some" | "many";

export type GenericObservation = {
  /**
   * Source of this observation
   */
  $source: string;
  /**
   * External ID of this observation
   */
  $id: string;
  /**
   * Type of this observation
   */
  $type: GenericObservationObservationType;
  /**
   * External URL to display as iframe
   */
  $externalURL?: string;
  /**
   * Snowpack stability that can be inferred from this observation
   */
  stability?: string;
  /**
   * Aspects corresponding with this observation
   */
  aspects?: Array<Aspect>;
  /**
   * Name of the author
   */
  authorName?: string;
  /**
   * Free-text content
   */
  content?: string;
  /**
   * Additional data (e.g. original data stored when fetching from external API)
   */
  $data?: {
    [key: string]: unknown;
  };
  /**
   * Elevation in meters
   */
  elevation?: number;
  /**
   * Lower bound of elevation in meters
   */
  elevationLowerBound?: number;
  /**
   * Upper bound of elevation in meters
   */
  elevationUpperBound?: number;
  /**
   * Date when the event occurred
   */
  eventDate?: string;
  /**
   * Location latitude (WGS 84)
   */
  latitude?: number;
  /**
   * Location name
   */
  locationName?: string;
  /**
   * Location longitude (WGS 84)
   */
  longitude?: number;
  /**
   * Micro-region code (possibly computed from latitude/longitude)
   */
  region?: string;
  /**
   * Date when the observation has been reported
   */
  reportDate?: string;
  /**
   * Avalanche problems corresponding with this observation
   */
  avalancheProblems?: Array<AvalancheProblem1>;
  /**
   * Danger patterns corresponding with this observation
   */
  dangerPatterns?: Array<DangerPattern>;
  /**
   * Important observations
   */
  importantObservation?: Array<GenericObservationImportantObservation>;
  /**
   * Additional information to display as table rows in the observation dialog
   */
  extraDialogRows?: {
    [key: string]: unknown;
  };
  /**
   * External image to display. Multiple images are persisted using line separator.
   */
  $externalImgs?: string;
  /**
   * Person involvement
   */
  personInvolvement?: GenericObservationPersonInvolvement;
  /**
   * Observations marked as deleted will no longer be returned in the list
   */
  $deleted?: boolean;
  /**
   * Allows modifying observations fetched from external sources
   */
  allowEdit?: boolean;
  /**
   * Danger source UUID
   */
  dangerSource?: DangerSource | null;
};

export type GenericObservationImportantObservation =
  | "SnowLine"
  | "SurfaceHoar"
  | "Graupel"
  | "StabilityTest"
  | "IceFormation"
  | "VeryLightNewSnow"
  | "ForBlog";

export type GenericObservationObservationType =
  | "SimpleObservation"
  | "Evaluation"
  | "Avalanche"
  | "Blasting"
  | "Closure"
  | "Profile"
  | "TimeSeries"
  | "Webcam"
  | "DrySnowfallLevel";

export type GenericObservationPersonInvolvement = "Dead" | "Injured" | "Uninjured" | "No" | "Unknown";

export type GlidingSnowActivity = "low" | "medium" | "high";

export type GrainShape =
  | "PP"
  | "MM"
  | "DF"
  | "RG"
  | "FC"
  | "DH"
  | "SH"
  | "MF"
  | "IF"
  | "PPco"
  | "PPnd"
  | "PPpl"
  | "PPsd"
  | "PPir"
  | "PPgp"
  | "PPhl"
  | "PPip"
  | "PPrm"
  | "MMrp"
  | "MMci"
  | "DFdc"
  | "DFbk"
  | "RGsr"
  | "RGlr"
  | "RGwp"
  | "RGxf"
  | "FCso"
  | "FCsf"
  | "FCxr"
  | "DHcp"
  | "DHpr"
  | "DHch"
  | "DHla"
  | "DHxr"
  | "SHsu"
  | "SHcv"
  | "SHxr"
  | "MFcl"
  | "MFpc"
  | "MFsl"
  | "MFcr"
  | "IFil"
  | "IFic"
  | "IFbi"
  | "IFrc"
  | "IFsc";

export type HandHardness = "fist" | "four_fingers" | "one_finger" | "pencil" | "knife" | "ice";

export type HazardSiteDistribution = "single" | "some" | "many" | "many_most" | "moderately_steep";

export type Incident = AbstractPersistentObject & {
  id?: string | null;
  createdAt?: string;
  updatedAt?: string;
  data?: {
    [key: string]: unknown;
  };
  publishedAt?: string;
  publicData?: {
    [key: string]: unknown;
  };
};

export type IncidentAttachment = {
  id: string;
  dateAdded: string;
  fileName: string;
  mediaType: string;
  dateCreated: string;
  credit: string;
  caption: string;
  altText: string;
  public: boolean;
  attachmentCategory: string;
  attachmentTags: Array<string>;
};

/**
 * The enum contains the ISO 639-1 codes for available languages.
 */
export type LanguageCode = "de" | "it" | "en" | "fr" | "es" | "ca" | "oc";

export type LocalServerInstance = {
  publishAt5PM: boolean;
  publishAt8AM: boolean;
  mapsPath: string;
  mapProductionUrl: string;
  pdfDirectory: string;
  htmlDirectory: string;
  mediaPath: string;
};

export type MatrixInformation = {
  artificialDangerRating?: DangerRating;
  artificialAvalancheSize?: AvalancheSize;
  artificialAvalancheReleaseProbability?: ArtificialAvalancheReleaseProbability;
  artificialHazardSiteDistribution?: HazardSiteDistribution;
  naturalDangerRating?: DangerRating;
  naturalAvalancheReleaseProbability?: NaturalAvalancheReleaseProbability;
  naturalHazardSiteDistribution?: HazardSiteDistribution;
};

export type NaturalAvalancheReleaseProbability = "one" | "two" | "three" | "four";

export type Position = "topleft" | "topright" | "bottomleft" | "bottomright";

export type Probability = "likely" | "possible" | "unlikely";

export type PublicationChecklistItem = AbstractPersistentObject & {
  id?: string | null;
  publicationChannel?: string;
  ok?: boolean;
  problemDescription?: string;
};

export type PublicationStrategyType = "publish" | "noMessages" | "minimalCAAML";

export type PushSubscription = {
  id?: number | null;
  subscribeDate?: string;
  auth?: string;
  p256dh?: string;
  endpoint?: string;
  language?: LanguageCode;
  region?: string;
  failedCount?: number;
};

export type Recognizability = "very_easy" | "easy" | "hard" | "very_hard";

/**
 * This class holds all information about one region.
 */
export type Region = {
  id?: string;
  microRegions?: number;
  subRegions?: Array<string>;
  superRegions?: Array<string>;
  neighborRegions?: Array<string>;
  languageConfigurations?: Array<RegionLanguageConfiguration>;
  staticUrl?: string;
  enabledLanguages?: Array<LanguageCode>;
  ttsLanguages?: Array<LanguageCode>;
  publishBulletins?: boolean;
  publishBlogs?: boolean;
  createCaamlV6?: boolean;
  createJson?: boolean;
  createMaps?: boolean;
  createPdf?: boolean;
  createSimpleHtml?: boolean;
  sendEmails?: boolean;
  sendTelegramMessages?: boolean;
  sendWhatsAppMessages?: boolean;
  sendPushNotifications?: boolean;
  enableMediaFile?: boolean;
  enableIcon?: boolean;
  enableAvalancheProblemCornices?: boolean;
  enableAvalancheProblemNoDistinctAvalancheProblem?: boolean;
  showMatrix?: boolean;
  enableStrategicMindset?: boolean;
  enableStressLevel?: boolean;
  pdfColor?: string;
  emailColor?: string;
  pdfMapYAmPm?: number;
  pdfMapYFd?: number;
  pdfMapWidthAmPm?: number;
  pdfMapWidthFd?: number;
  pdfMapHeight?: number;
  pdfFooterLogo?: boolean;
  pdfFooterLogoColorPath?: string;
  pdfFooterLogoBwPath?: string;
  geoDataDirectory?: string;
  mapLogoPosition?: Position;
  imageColorbarColorPath?: string;
  imageColorbarBwPath?: string;
  enableDangerSources?: boolean;
  enableObservations?: boolean;
  enableIncidents?: boolean;
  enableModelling?: boolean;
  enabledTextcatFields?: Array<TextPart>;
  enabledEditableFields?: Array<TextPart>;
  enableLineaExport?: boolean;
  defaultLang?: LanguageCode;
  logoPath?: string;
  logoBwPath?: string;
  coatOfArms?: string;
  serverImagesUrl?: string;
  educationUrl?: string;
  awsomeUrl?: string;
};

export type RegionLanguageConfiguration = {
  lang?: LanguageCode;
  websiteName?: string;
  warningServiceName?: string;
  warningServiceEmail?: string;
  url?: string;
  urlWithDate?: string;
};

export type Role = "SUPERADMIN" | "ADMIN" | "FORECASTER" | "FOREMAN" | "OBSERVER";

/**
 * This class holds all information about a server instance.
 */
export type ServerInstance = {
  id?: number | null;
  name?: string;
  apiUrl?: string;
  userName?: string;
  password?: string;
  externalServer?: boolean;
};

export type ServerInstanceServiceServerVersionInfo = {
  version: string;
};

export type SlopeGradient = "moderately_steep" | "steep" | "very_steep" | "extremely_steep";

export type SnowpackPosition = "upper" | "middle" | "lower" | "ground";

export type SnowpackStability = "good" | "fair" | "poor" | "very_poor";

export type StatusInformation = {
  ok: boolean;
  title: string;
  message: string;
};

export type StrategicMindset =
  | "assessment"
  | "stepping_out"
  | "status_quo"
  | "stepping_back"
  | "entrenchment"
  | "free_ride"
  | "high_alert"
  | "spring_diurnal";

export type StressLevel = {
  date?: string;
  stressLevel?: number;
  lastUpdated?: string;
};

export type SubscriptionServiceEmailSubscription = {
  email: string;
  regions: string;
  language: LanguageCode;
};

export type Tendency = "decreasing" | "steady" | "increasing";

export type TerrainType =
  | "gullies_and_bowls"
  | "adjacent_to_ridgelines"
  | "distant_from_ridgelines"
  | "in_the_vicinity_of_peaks"
  | "pass_areas"
  | "shady_slopes"
  | "sunny_slopes"
  | "grassy_slopes"
  | "cut_slopes"
  | "wind_loaded_slopes"
  | "base_of_rock_walls"
  | "behind_abrupt_changes_in_the_terrain"
  | "transitions_into_gullies_and_bowls"
  | "areas_where_the_snow_cover_is_rather_shallow"
  | "transitions_from_a_shallow_to_a_deep_snowpack"
  | "highly_frequented_off_piste_terrain"
  | "little_used_backcountry_terrain"
  | "places_that_are_protected_from_the_wind"
  | "regions_exposed_to_the_foehn_wind"
  | "regions_with_a_lot_of_snow"
  | "regions_exposed_to_precipitation"
  | "regions_exposed_to_heavier_precipitation";

export type TextPart =
  | "generalHeadlineComment"
  | "highlights"
  | "avActivityHighlights"
  | "avActivityComment"
  | "snowpackStructureHighlights"
  | "snowpackStructureComment"
  | "synopsisHighlights"
  | "synopsisComment"
  | "tendencyComment"
  | "travelAdvisoryHighlights"
  | "travelAdvisoryComment";

export type Thickness = "thick" | "thin";

export type User = {
  /**
   * Email address of the user
   */
  email?: string;
  /**
   * Password of the user
   */
  password?: string;
  /**
   * Name of the user
   */
  name?: string;
  roles?: Array<Role>;
  regions?: Array<string>;
  /**
   * Image of the user
   */
  image?: string;
  /**
   * Organization the user works for
   */
  organization?: string;
  /**
   * Preferred language of the user
   */
  languageCode?: LanguageCode;
  deleted?: boolean;
};

export type UserServiceChangePassword = {
  oldPassword: string;
  newPassword: string;
};

export type UserServiceCheckPassword = {
  password: string;
};

export type UserServiceResetPassword = {
  newPassword: string;
};

export type Wetness = "wet" | "moist" | "dry";

export type IndexData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/";
};

export type IndexResponses = {
  /**
   * index 200 response
   */
  200: string;
};

export type IndexResponse = IndexResponses[keyof IndexResponses];

export type LoginData = {
  body: AuthenticationServiceCredentials;
  path?: never;
  query?: never;
  url: "/authentication";
};

export type LoginResponses = {
  /**
   * login 200 response
   */
  200: AuthenticationServiceAuthenticationResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type TestAuthData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/authentication/test";
};

export type TestAuthResponses = {
  /**
   * testAuth 200 response
   */
  200: AuthenticationServiceUsername;
};

export type TestAuthResponse = TestAuthResponses[keyof TestAuthResponses];

export type GetBlogPostData = {
  body?: never;
  path?: never;
  query: {
    region?: string;
    lang?: LanguageCode;
    id: string;
  };
  url: "/blogs/post";
};

export type GetBlogPostResponses = {
  /**
   * getBlogPost 200 response
   */
  200: BlogItem;
};

export type GetBlogPostResponse = GetBlogPostResponses[keyof GetBlogPostResponses];

export type GetBlogPostsData = {
  body?: never;
  path?: never;
  query: {
    region?: string;
    lang?: LanguageCode;
    searchText: string;
    searchCategory: string;
    startDate: string;
    endDate: string;
  };
  url: "/blogs/posts";
};

export type GetBlogPostsResponses = {
  /**
   * getBlogPosts 200 response
   */
  200: Array<BlogItem>;
};

export type GetBlogPostsResponse = GetBlogPostsResponses[keyof GetBlogPostsResponses];

export type SendLatestBlogPostData = {
  body?: never;
  path?: never;
  query: {
    region: string;
    lang: LanguageCode;
  };
  url: "/blogs/publish/latest";
};

export type SendLatestBlogPostResponses = {
  /**
   * sendLatestBlogPost 200 response
   */
  200: unknown;
};

export type SendLatestBlogPostEmailData = {
  body?: never;
  path?: never;
  query: {
    region: string;
    lang: LanguageCode;
  };
  url: "/blogs/publish/latest/email";
};

export type SendLatestBlogPostEmailResponses = {
  /**
   * sendLatestBlogPostEmail 200 response
   */
  200: unknown;
};

export type SendLatestBlogPostPushData = {
  body?: never;
  path?: never;
  query: {
    region: string;
    lang: LanguageCode;
  };
  url: "/blogs/publish/latest/push";
};

export type SendLatestBlogPostPushResponses = {
  /**
   * sendLatestBlogPostPush 200 response
   */
  200: unknown;
};

export type SendLatestBlogPostTelegramData = {
  body?: never;
  path?: never;
  query: {
    region: string;
    lang: LanguageCode;
  };
  url: "/blogs/publish/latest/telegram";
};

export type SendLatestBlogPostTelegramResponses = {
  /**
   * sendLatestBlogPostTelegram 200 response
   */
  200: unknown;
};

export type SendLatestBlogPostWhatsAppData = {
  body?: never;
  path?: never;
  query: {
    region: string;
    lang: LanguageCode;
  };
  url: "/blogs/publish/latest/whatsapp";
};

export type SendLatestBlogPostWhatsAppResponses = {
  /**
   * sendLatestBlogPostWhatsApp 200 response
   */
  200: unknown;
};

export type GetPublishedJsonBulletins0Data = {
  body?: never;
  path?: never;
  query: {
    version?: CaamlVersion;
    regions: Array<string>;
    region: string;
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    date: string;
    lang: LanguageCode;
  };
  url: "/bulletins";
};

export type GetPublishedJsonBulletins0Responses = {
  /**
   * bulletins
   */
  200: Array<AvalancheBulletin>;
};

export type GetPublishedJsonBulletins0Response =
  GetPublishedJsonBulletins0Responses[keyof GetPublishedJsonBulletins0Responses];

export type CreateJsonBulletinsData = {
  body: Array<AvalancheBulletin>;
  path?: never;
  query: {
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    date: string;
    region: string;
  };
  url: "/bulletins";
};

export type CreateJsonBulletinsResponses = {
  /**
   * createJSONBulletins 200 response
   */
  200: Array<AvalancheBulletin>;
};

export type CreateJsonBulletinsResponse = CreateJsonBulletinsResponses[keyof CreateJsonBulletinsResponses];

export type CreateJsonBulletinData = {
  body: AvalancheBulletin;
  path?: never;
  query: {
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    date: string;
    region: string;
  };
  url: "/bulletins";
};

export type CreateJsonBulletinResponses = {
  /**
   * createJSONBulletin 200 response
   */
  200: Array<AvalancheBulletin>;
};

export type CreateJsonBulletinResponse = CreateJsonBulletinResponses[keyof CreateJsonBulletinResponses];

export type GetPublishedCaamlBulletinsData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    date: string;
    regions: Array<string>;
    lang: LanguageCode;
    version?: CaamlVersion;
  };
  url: "/bulletins/caaml";
};

export type GetPublishedCaamlBulletinsResponses = {
  /**
   * getPublishedCaamlBulletins 200 response
   */
  200: Blob | File;
};

export type GetPublishedCaamlBulletinsResponse =
  GetPublishedCaamlBulletinsResponses[keyof GetPublishedCaamlBulletinsResponses];

export type GetPublishedCaamlJsonBulletinsData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    date: string;
    regions: Array<string>;
    lang: LanguageCode;
    version?: CaamlVersion;
  };
  url: "/bulletins/caaml/json";
};

export type GetPublishedCaamlJsonBulletinsResponses = {
  /**
   * getPublishedCaamlJsonBulletins 200 response
   */
  200: string;
};

export type GetPublishedCaamlJsonBulletinsResponse =
  GetPublishedCaamlJsonBulletinsResponses[keyof GetPublishedCaamlJsonBulletinsResponses];

export type CheckBulletinsData = {
  body?: never;
  path?: never;
  query: {
    region: string;
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    date: string;
  };
  url: "/bulletins/check";
};

export type CheckBulletinsResponses = {
  /**
   * checkBulletins 200 response
   */
  200: Array<string>;
};

export type CheckBulletinsResponse = CheckBulletinsResponses[keyof CheckBulletinsResponses];

export type GetJsonBulletinsData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    date: string;
    regions: Array<string>;
  };
  url: "/bulletins/edit";
};

export type GetJsonBulletinsResponses = {
  /**
   * bulletins
   */
  200: Array<AvalancheBulletin>;
};

export type GetJsonBulletinsResponse = GetJsonBulletinsResponses[keyof GetJsonBulletinsResponses];

export type GetCaamlJsonBulletinsData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    date: string;
    regions: Array<string>;
    lang: LanguageCode;
    version?: CaamlVersion;
  };
  url: "/bulletins/edit/caaml/json";
};

export type GetCaamlJsonBulletinsResponses = {
  /**
   * getCaamlJsonBulletins 200 response
   */
  200: string;
};

export type GetCaamlJsonBulletinsResponse = GetCaamlJsonBulletinsResponses[keyof GetCaamlJsonBulletinsResponses];

export type GetHighestDangerRatingData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    date: string;
    regions: Array<string>;
  };
  url: "/bulletins/highest";
};

export type GetHighestDangerRatingResponses = {
  /**
   * latest
   */
  200: AvalancheBulletinServiceHighest;
};

export type GetHighestDangerRatingResponse = GetHighestDangerRatingResponses[keyof GetHighestDangerRatingResponses];

export type GetPublishedJsonBulletinsData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    date: string;
    regions: Array<string>;
    lang: LanguageCode;
  };
  url: "/bulletins/json";
};

export type GetPublishedJsonBulletinsResponses = {
  /**
   * bulletins
   */
  200: Array<AvalancheBulletin>;
};

export type GetPublishedJsonBulletinsResponse =
  GetPublishedJsonBulletinsResponses[keyof GetPublishedJsonBulletinsResponses];

export type GetLatestData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/bulletins/latest";
};

export type GetLatestResponses = {
  /**
   * getLatest 200 response
   */
  200: AvalancheBulletinServiceLatestBulletin;
};

export type GetLatestResponse = GetLatestResponses[keyof GetLatestResponses];

export type GetPublishedBulletinsAsPdfData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    date: string;
    bulletinId?: string | null;
    microRegionId?: string | null;
    region: string;
    grayscale: boolean;
    lang: LanguageCode;
  };
  url: "/bulletins/pdf";
};

export type GetPublishedBulletinsAsPdfResponses = {
  /**
   * getPublishedBulletinsAsPDF 200 response
   */
  200: Blob | File;
};

export type GetPublishedBulletinsAsPdfResponse =
  GetPublishedBulletinsAsPdfResponses[keyof GetPublishedBulletinsAsPdfResponses];

export type UploadBulletinPhotoData = {
  body: {
    file?: Blob | File;
  };
  path?: never;
  query: {
    region: string;
  };
  url: "/bulletins/photo";
};

export type UploadBulletinPhotoResponses = {
  /**
   * uploadBulletinPhoto 200 response
   */
  200: AvalancheBulletinCustomDataBulletinPhoto;
};

export type UploadBulletinPhotoResponse = UploadBulletinPhotoResponses[keyof UploadBulletinPhotoResponses];

export type GetPreviewPdfData = {
  body: Array<AvalancheBulletin>;
  path?: never;
  query: {
    region: string;
    lang: LanguageCode;
  };
  url: "/bulletins/preview";
};

export type GetPreviewPdfResponses = {
  /**
   * getPreviewPdf 200 response
   */
  200: Blob | File;
};

export type GetPreviewPdfResponse = GetPreviewPdfResponses[keyof GetPreviewPdfResponses];

export type PublishBulletinsData = {
  body?: never;
  path?: never;
  query: {
    region: string;
    strategy?: PublicationStrategyType;
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    date: string;
  };
  url: "/bulletins/publish";
};

export type PublishBulletinsResponses = {
  /**
   * publishBulletins 200 response
   */
  200: unknown;
};

export type PublishAllBulletinsData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    date: string;
    strategy?: PublicationStrategyType;
  };
  url: "/bulletins/publish/all";
};

export type PublishAllBulletinsResponses = {
  /**
   * publishAllBulletins 200 response
   */
  200: unknown;
};

export type SendEmailData = {
  body?: never;
  path?: never;
  query: {
    region: string;
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    date: string;
    lang?: LanguageCode | null;
  };
  url: "/bulletins/publish/email";
};

export type SendEmailResponses = {
  /**
   * sendEmail 200 response
   */
  200: unknown;
};

export type TriggerPushNotificationsData = {
  body?: never;
  path?: never;
  query: {
    region: string;
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    date: string;
    lang?: LanguageCode | null;
  };
  url: "/bulletins/publish/push";
};

export type TriggerPushNotificationsResponses = {
  /**
   * triggerPushNotifications 200 response
   */
  200: unknown;
};

export type TriggerTelegramChannelData = {
  body?: never;
  path?: never;
  query: {
    region: string;
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    date: string;
    lang?: LanguageCode | null;
  };
  url: "/bulletins/publish/telegram";
};

export type TriggerTelegramChannelResponses = {
  /**
   * triggerTelegramChannel 200 response
   */
  200: unknown;
};

export type TriggerWhatsAppChannelData = {
  body?: never;
  path?: never;
  query: {
    region: string;
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    date: string;
    lang?: LanguageCode | null;
  };
  url: "/bulletins/publish/whatsapp";
};

export type TriggerWhatsAppChannelResponses = {
  /**
   * triggerWhatsAppChannel 200 response
   */
  200: unknown;
};

export type GetStatusData = {
  body?: never;
  path?: never;
  query: {
    region: string;
    timezone: string;
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    startDate: string;
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    endDate: string;
  };
  url: "/bulletins/status";
};

export type GetStatusResponses = {
  /**
   * getStatus 200 response
   */
  200: Array<AvalancheBulletinStatusServiceStatus>;
};

export type GetStatusResponse = GetStatusResponses[keyof GetStatusResponses];

export type GetInternalStatusData = {
  body?: never;
  path?: never;
  query: {
    region: string;
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    startDate: string;
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    endDate: string;
  };
  url: "/bulletins/status/internal";
};

export type GetInternalStatusResponses = {
  /**
   * getInternalStatus 200 response
   */
  200: Array<AvalancheBulletinStatusServiceStatus>;
};

export type GetInternalStatusResponse = GetInternalStatusResponses[keyof GetInternalStatusResponses];

export type GetPublicationStatusData = {
  body?: never;
  path?: never;
  query: {
    region: string;
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    date: string;
  };
  url: "/bulletins/status/publication";
};

export type GetPublicationStatusResponses = {
  /**
   * getPublicationStatus 200 response
   */
  200: AvalancheBulletinStatusServiceStatus;
};

export type GetPublicationStatusResponse = GetPublicationStatusResponses[keyof GetPublicationStatusResponses];

export type SubmitBulletinsData = {
  body?: never;
  path?: never;
  query: {
    region: string;
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    date: string;
  };
  url: "/bulletins/submit";
};

export type SubmitBulletinsResponses = {
  /**
   * submitBulletins 200 response
   */
  200: unknown;
};

export type DeleteJsonBulletinData = {
  body?: never;
  path: {
    bulletinId: string;
  };
  query: {
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    date: string;
    region: string;
  };
  url: "/bulletins/{bulletinId}";
};

export type DeleteJsonBulletinResponses = {
  /**
   * deleteJSONBulletin 200 response
   */
  200: Array<AvalancheBulletin>;
};

export type DeleteJsonBulletinResponse = DeleteJsonBulletinResponses[keyof DeleteJsonBulletinResponses];

export type GetJsonBulletinData = {
  body?: never;
  path: {
    bulletinId: string;
  };
  query?: never;
  url: "/bulletins/{bulletinId}";
};

export type GetJsonBulletinResponses = {
  /**
   * bulletin
   */
  200: AvalancheBulletin;
};

export type GetJsonBulletinResponse = GetJsonBulletinResponses[keyof GetJsonBulletinResponses];

export type UpdateJsonBulletinData = {
  body: AvalancheBulletin;
  path: {
    bulletinId: string;
  };
  query: {
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    date: string;
    region: string;
  };
  url: "/bulletins/{bulletinId}";
};

export type UpdateJsonBulletinResponses = {
  /**
   * updateJSONBulletin 200 response
   */
  200: Array<AvalancheBulletin>;
};

export type UpdateJsonBulletinResponse = UpdateJsonBulletinResponses[keyof UpdateJsonBulletinResponses];

export type GetChecklistsData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    date: string;
    region: string;
  };
  url: "/checklist";
};

export type GetChecklistsResponses = {
  /**
   * getChecklists 200 response
   */
  200: Array<ChecklistServiceChecklist>;
};

export type GetChecklistsResponse = GetChecklistsResponses[keyof GetChecklistsResponses];

export type SaveChecklistData = {
  body: ChecklistServiceChecklist;
  path?: never;
  query: {
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    date: string;
    region: string;
  };
  url: "/checklist";
};

export type SaveChecklistResponses = {
  /**
   * saveChecklist 200 response
   */
  200: ChecklistServiceChecklist;
};

export type SaveChecklistResponse = SaveChecklistResponses[keyof SaveChecklistResponses];

export type GetDangerSourcesData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    date: string;
    region: string;
  };
  url: "/danger-sources";
};

export type GetDangerSourcesResponses = {
  /**
   * danger-sources
   */
  200: Array<DangerSource>;
};

export type GetDangerSourcesResponse = GetDangerSourcesResponses[keyof GetDangerSourcesResponses];

export type SaveDangerSourceData = {
  body: DangerSource;
  path?: never;
  query?: never;
  url: "/danger-sources";
};

export type SaveDangerSourceResponses = {
  /**
   * saveDangerSource 200 response
   */
  200: DangerSource;
};

export type SaveDangerSourceResponse = SaveDangerSourceResponses[keyof SaveDangerSourceResponses];

export type GetVariantsData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    date: string;
    region: string;
  };
  url: "/danger-sources/edit";
};

export type GetVariantsResponses = {
  /**
   * danger-sources
   */
  200: Array<DangerSourceVariant>;
};

export type GetVariantsResponse = GetVariantsResponses[keyof GetVariantsResponses];

export type GetInternalStatus1Data = {
  body?: never;
  path?: never;
  query: {
    region: string;
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    startDate: string;
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    endDate: string;
  };
  url: "/danger-sources/status";
};

export type GetInternalStatus1Responses = {
  /**
   * getInternalStatus_1 200 response
   */
  200: Array<DangerSourceVariantsStatus>;
};

export type GetInternalStatus1Response = GetInternalStatus1Responses[keyof GetInternalStatus1Responses];

export type SaveDangerSourceVariantData = {
  body: DangerSourceVariant;
  path?: never;
  query: {
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    date: string;
    region: string;
  };
  url: "/danger-sources/variants";
};

export type SaveDangerSourceVariantResponses = {
  /**
   * saveDangerSourceVariant 200 response
   */
  200: DangerSourceVariant;
};

export type SaveDangerSourceVariantResponse = SaveDangerSourceVariantResponses[keyof SaveDangerSourceVariantResponses];

export type ReplaceVariantsData = {
  body: Array<DangerSourceVariant>;
  path?: never;
  query: {
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    date: string;
    region: string;
  };
  url: "/danger-sources/variants/replace";
};

export type ReplaceVariantsResponses = {
  /**
   * replaceVariants 200 response
   */
  200: Array<DangerSourceVariant>;
};

export type ReplaceVariantsResponse = ReplaceVariantsResponses[keyof ReplaceVariantsResponses];

export type DeleteVariantData = {
  body?: never;
  path: {
    variantId: string;
  };
  query: {
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    date: string;
    region: string;
  };
  url: "/danger-sources/variants/{variantId}";
};

export type DeleteVariantResponses = {
  /**
   * deleteVariant 200 response
   */
  200: Array<DangerSourceVariant>;
};

export type DeleteVariantResponse = DeleteVariantResponses[keyof DeleteVariantResponses];

export type GetVariantByIdData = {
  body?: never;
  path: {
    variantId: string;
  };
  query?: never;
  url: "/danger-sources/variants/{variantId}";
};

export type GetVariantByIdResponses = {
  /**
   * variant
   */
  200: DangerSourceVariant;
};

export type GetVariantByIdResponse = GetVariantByIdResponses[keyof GetVariantByIdResponses];

export type GetVariantsForDangerSourceData = {
  body?: never;
  path: {
    dangerSourceId: string;
  };
  query: {
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    date: string;
    region: string;
  };
  url: "/danger-sources/{dangerSourceId}/edit";
};

export type GetVariantsForDangerSourceResponses = {
  /**
   * danger-sources
   */
  200: Array<DangerSourceVariant>;
};

export type GetVariantsForDangerSourceResponse =
  GetVariantsForDangerSourceResponses[keyof GetVariantsForDangerSourceResponses];

export type AddSubscriberData = {
  body: SubscriptionServiceEmailSubscription;
  path?: never;
  query?: never;
  url: "/email/subscribe";
};

export type AddSubscriberResponses = {
  /**
   * addSubscriber 200 response
   */
  200: unknown;
};

export type GetIncidentsData = {
  body?: never;
  path?: never;
  query: {
    region: string;
    /**
     * Season year, expanded to yyyy-10-01 until (yyyy+1)-10-01
     */
    seasonYear: number;
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    startDate?: string | null;
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    endDate?: string | null;
  };
  url: "/incidents";
};

export type GetIncidentsResponses = {
  /**
   * getIncidents 200 response
   */
  200: string;
};

export type GetIncidentsResponse = GetIncidentsResponses[keyof GetIncidentsResponses];

export type CreateIncidentData = {
  body: string;
  path?: never;
  query: {
    region: string;
  };
  url: "/incidents";
};

export type CreateIncidentResponses = {
  /**
   * createIncident 200 response
   */
  200: Incident;
};

export type CreateIncidentResponse = CreateIncidentResponses[keyof CreateIncidentResponses];

export type DeleteIncidentData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/incidents/{id}";
};

export type DeleteIncidentResponses = {
  /**
   * deleteIncident 200 response
   */
  200: unknown;
};

export type GetIncidentData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/incidents/{id}";
};

export type GetIncidentResponses = {
  /**
   * getIncident 200 response
   */
  200: string;
};

export type GetIncidentResponse = GetIncidentResponses[keyof GetIncidentResponses];

export type UpdateIncidentData = {
  body: string;
  path: {
    id: string;
  };
  query?: never;
  url: "/incidents/{id}";
};

export type UpdateIncidentResponses = {
  /**
   * updateIncident 200 response
   */
  200: Incident;
};

export type UpdateIncidentResponse = UpdateIncidentResponses[keyof UpdateIncidentResponses];

export type UploadIncidentAttachmentData = {
  body: {
    file?: Blob | File;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/incidents/{id}/attachment";
};

export type UploadIncidentAttachmentResponses = {
  /**
   * uploadIncidentAttachment 200 response
   */
  200: IncidentAttachment;
};

export type UploadIncidentAttachmentResponse =
  UploadIncidentAttachmentResponses[keyof UploadIncidentAttachmentResponses];

export type DeleteIncidentAttachmentData = {
  body?: never;
  path: {
    id: string;
    attachmentId: string;
  };
  query?: never;
  url: "/incidents/{id}/attachment/{attachmentId}";
};

export type DeleteIncidentAttachmentResponses = {
  /**
   * deleteIncidentAttachment 200 response
   */
  200: unknown;
};

export type GetIncidentAttachmentData = {
  body?: never;
  path: {
    id: string;
    attachmentId: string;
  };
  query?: never;
  url: "/incidents/{id}/attachment/{attachmentId}";
};

export type GetIncidentAttachmentResponses = {
  /**
   * getIncidentAttachment 200 response
   */
  200: Blob | File;
};

export type GetIncidentAttachmentResponse = GetIncidentAttachmentResponses[keyof GetIncidentAttachmentResponses];

export type UnpublishIncidentData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/incidents/{id}/publish";
};

export type UnpublishIncidentResponses = {
  /**
   * unpublishIncident 200 response
   */
  200: Incident;
};

export type UnpublishIncidentResponse = UnpublishIncidentResponses[keyof UnpublishIncidentResponses];

export type PublishIncidentData = {
  body: string;
  path: {
    id: string;
  };
  query?: never;
  url: "/incidents/{id}/publish";
};

export type PublishIncidentResponses = {
  /**
   * publishIncident 200 response
   */
  200: Incident;
};

export type PublishIncidentResponse = PublishIncidentResponses[keyof PublishIncidentResponses];

export type SaveMediaFileData = {
  body: {
    text?: string;
    file?: Blob | File;
  };
  path?: never;
  query: {
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    date: string;
    region: string;
    lang: LanguageCode;
    important: boolean;
  };
  url: "/media";
};

export type SaveMediaFileResponses = {
  /**
   * saveMediaFile 200 response
   */
  200: unknown;
};

export type GetRssFeedData = {
  body?: never;
  path?: never;
  query?: {
    region?: string;
    lang?: LanguageCode;
  };
  url: "/media/rss";
};

export type GetRssFeedResponses = {
  /**
   * getRssFeed 200 response
   */
  200: string;
};

export type GetRssFeedResponse = GetRssFeedResponses[keyof GetRssFeedResponses];

export type DeleteGenericObservationData = {
  body: GenericObservation;
  path?: never;
  query?: never;
  url: "/observations";
};

export type DeleteGenericObservationResponses = {
  /**
   * deleteGenericObservation 200 response
   */
  200: unknown;
};

export type GetGenericObservationsData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    startDate: string;
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    endDate: string;
  };
  url: "/observations";
};

export type GetGenericObservationsResponses = {
  /**
   * getGenericObservations 200 response
   */
  200: Array<GenericObservation>;
};

export type GetGenericObservationsResponse = GetGenericObservationsResponses[keyof GetGenericObservationsResponses];

export type SaveOrUpdateGenericObservationData = {
  body: GenericObservation;
  path?: never;
  query?: never;
  url: "/observations";
};

export type SaveOrUpdateGenericObservationResponses = {
  /**
   * saveOrUpdateGenericObservation 200 response
   */
  200: unknown;
};

export type GetGenericObservationData = {
  body?: never;
  path?: never;
  query: {
    source: string;
    id: string;
  };
  url: "/observations/:source/:id";
};

export type GetGenericObservationResponses = {
  /**
   * getGenericObservation 200 response
   */
  200: GenericObservation;
};

export type GetGenericObservationResponse = GetGenericObservationResponses[keyof GetGenericObservationResponses];

export type GetOpenApiJsonData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/openapi.json";
};

export type GetOpenApiJsonResponses = {
  /**
   * getOpenApiJson 200 response
   */
  200: {
    [key: string]: unknown;
  };
};

export type GetOpenApiJsonResponse = GetOpenApiJsonResponses[keyof GetOpenApiJsonResponses];

export type GetOpenApiData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/openapi.yml";
};

export type GetOpenApiResponses = {
  /**
   * getOpenApi 200 response
   */
  200: string;
};

export type GetOpenApiResponse = GetOpenApiResponses[keyof GetOpenApiResponses];

export type KeyData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/push/key";
};

export type KeyResponses = {
  /**
   * key 200 response
   */
  200: {
    [key: string]: unknown;
  };
};

export type KeyResponse = KeyResponses[keyof KeyResponses];

export type SubscribeData = {
  body: PushSubscription;
  path?: never;
  query?: never;
  url: "/push/subscribe";
};

export type SubscribeResponses = {
  /**
   * subscribe 200 response
   */
  200: unknown;
};

export type UnsubscribeData = {
  body: PushSubscription;
  path?: never;
  query?: never;
  url: "/push/unsubscribe";
};

export type UnsubscribeResponses = {
  /**
   * unsubscribe 200 response
   */
  200: unknown;
};

export type GetRegionsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/regions";
};

export type GetRegionsResponses = {
  /**
   * getRegions 200 response
   */
  200: Array<Region>;
};

export type GetRegionsResponse = GetRegionsResponses[keyof GetRegionsResponses];

export type SaveRegionData = {
  body: string;
  path?: never;
  query?: never;
  url: "/regions";
};

export type SaveRegionResponses = {
  /**
   * saveRegion 200 response
   */
  200: Region;
};

export type SaveRegionResponse = SaveRegionResponses[keyof SaveRegionResponses];

export type GetRegionData = {
  body?: never;
  path?: never;
  query: {
    region: string;
  };
  url: "/regions/region";
};

export type GetRegionResponses = {
  /**
   * getRegion 200 response
   */
  200: Region;
};

export type GetRegionResponse = GetRegionResponses[keyof GetRegionResponses];

export type GetLocalServerConfigurationData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/server";
};

export type GetLocalServerConfigurationResponses = {
  /**
   * configuration
   */
  200: LocalServerInstance;
};

export type GetLocalServerConfigurationResponse =
  GetLocalServerConfigurationResponses[keyof GetLocalServerConfigurationResponses];

export type SaveServerConfigurationData = {
  body: ServerInstance;
  path?: never;
  query?: never;
  url: "/server";
};

export type SaveServerConfigurationResponses = {
  /**
   * saveServerConfiguration 200 response
   */
  200: ServerInstance;
};

export type SaveServerConfigurationResponse = SaveServerConfigurationResponses[keyof SaveServerConfigurationResponses];

export type GetExternalServerConfigurationsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/server/external";
};

export type GetExternalServerConfigurationsResponses = {
  /**
   * configuration
   */
  200: Array<ServerInstance>;
};

export type GetExternalServerConfigurationsResponse =
  GetExternalServerConfigurationsResponses[keyof GetExternalServerConfigurationsResponses];

export type GetServerVersionInfoData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/server/info";
};

export type GetServerVersionInfoResponses = {
  /**
   * server version info
   */
  200: ServerInstanceServiceServerVersionInfo;
};

export type GetServerVersionInfoResponse = GetServerVersionInfoResponses[keyof GetServerVersionInfoResponses];

export type GetBulletinCsvData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    startDate: string;
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    endDate: string;
    lang: LanguageCode;
    extended?: boolean;
    duplicate?: boolean;
    regions: Array<string>;
    obsoleteMatrix?: boolean;
  };
  url: "/statistics";
};

export type GetBulletinCsvResponses = {
  /**
   * getBulletinCsv 200 response
   */
  200: Blob | File;
};

export type GetBulletinCsvResponse = GetBulletinCsvResponses[keyof GetBulletinCsvResponses];

export type GetDangerSourceCsvData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    startDate: string;
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    endDate: string;
  };
  url: "/statistics/danger-sources";
};

export type GetDangerSourceCsvResponses = {
  /**
   * getDangerSourceCsv 200 response
   */
  200: Blob | File;
};

export type GetDangerSourceCsvResponse = GetDangerSourceCsvResponses[keyof GetDangerSourceCsvResponses];

export type SaveVirtualRealityStatisticsData = {
  body: string;
  path?: never;
  query?: never;
  url: "/statistics/vr";
};

export type SaveVirtualRealityStatisticsResponses = {
  /**
   * saveVirtualRealityStatistics 200 response
   */
  200: unknown;
};

export type GetStatus1Data = {
  body?: never;
  path?: never;
  query?: never;
  url: "/status/channels";
};

export type GetStatus1Responses = {
  /**
   * getStatus_1 200 response
   */
  200: Array<StatusInformation>;
};

export type GetStatus1Response = GetStatus1Responses[keyof GetStatus1Responses];

export type TriggerStatusChecksData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/status/channels";
};

export type TriggerStatusChecksResponses = {
  /**
   * triggerStatusChecks 200 response
   */
  200: Array<StatusInformation>;
};

export type TriggerStatusChecksResponse = TriggerStatusChecksResponses[keyof TriggerStatusChecksResponses];

export type GetUsersData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/user";
};

export type GetUsersResponses = {
  /**
   * getUsers 200 response
   */
  200: Array<User>;
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type SaveUserData = {
  body: User;
  path?: never;
  query?: never;
  url: "/user";
};

export type SaveUserResponses = {
  /**
   * saveUser 200 response
   */
  200: User;
};

export type SaveUserResponse = SaveUserResponses[keyof SaveUserResponses];

export type ChangePasswordData = {
  body: UserServiceChangePassword;
  path?: never;
  query?: never;
  url: "/user/change";
};

export type ChangePasswordResponses = {
  /**
   * changePassword 200 response
   */
  200: unknown;
};

export type CheckPasswordData = {
  body: UserServiceCheckPassword;
  path?: never;
  query?: never;
  url: "/user/check";
};

export type CheckPasswordResponses = {
  /**
   * checkPassword 200 response
   */
  200: unknown;
};

export type GetRegions1Data = {
  body?: never;
  path?: never;
  query?: never;
  url: "/user/regions";
};

export type GetRegions1Responses = {
  /**
   * getRegions_1 200 response
   */
  200: Array<string>;
};

export type GetRegions1Response = GetRegions1Responses[keyof GetRegions1Responses];

export type GetRolesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/user/roles";
};

export type GetRolesResponses = {
  /**
   * getRoles 200 response
   */
  200: Role;
};

export type GetRolesResponse = GetRolesResponses[keyof GetRolesResponses];

export type GetStressLevelsData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    startDate: string;
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    endDate: string;
  };
  url: "/user/stress-level";
};

export type GetStressLevelsResponses = {
  /**
   * getStressLevels 200 response
   */
  200: Array<StressLevel>;
};

export type GetStressLevelsResponse = GetStressLevelsResponses[keyof GetStressLevelsResponses];

export type PostStressLevelData = {
  body: StressLevel;
  path?: never;
  query?: never;
  url: "/user/stress-level";
};

export type PostStressLevelResponses = {
  /**
   * postStressLevel 200 response
   */
  200: StressLevel;
};

export type PostStressLevelResponse = PostStressLevelResponses[keyof PostStressLevelResponses];

export type GetTeamStressLevelsData = {
  body?: never;
  path?: never;
  query: {
    region: string;
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    startDate: string;
    /**
     * Date in the format yyyy-MM-dd'T'HH:mm:ssZZ
     */
    endDate: string;
  };
  url: "/user/stress-level/team";
};

export type GetTeamStressLevelsResponses = {
  /**
   * getTeamStressLevels 200 response
   */
  200: {
    [key: string]: Array<StressLevel>;
  };
};

export type GetTeamStressLevelsResponse = GetTeamStressLevelsResponses[keyof GetTeamStressLevelsResponses];

export type DeleteUserData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/user/{id}";
};

export type DeleteUserResponses = {
  /**
   * deleteUser 200 response
   */
  200: unknown;
};

export type ResetPasswordData = {
  body: UserServiceResetPassword;
  path: {
    id: string;
  };
  query?: never;
  url: "/user/{id}/reset";
};

export type ResetPasswordResponses = {
  /**
   * resetPassword 200 response
   */
  200: unknown;
};
