// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

export const zAbstractPersistentObject = z.object({
  id: z.string().nullish(),
});

export const zArtificialAvalancheReleaseProbability = z.enum(["one", "two", "three", "four"]);

export const zAspect = z.enum(["N", "NE", "E", "SE", "S", "SW", "W", "NW"]);

export const zAuthenticationServiceCredentials = z.object({
  username: z.string(),
  password: z.string(),
});

export const zAuthenticationServiceUsername = z.object({
  username: z.string(),
});

export const zAvalancheBulletinValidity = z.object({
  from: z.iso.datetime().optional(),
  until: z.iso.datetime().optional(),
});

export const zAvalancheBulletinCustomDataBulletinPhoto = z.object({
  url: z.string(),
  copyright: z.string().optional(),
  date: z.iso.date().optional(),
  microRegionId: z.string().optional(),
  locationName: z.string().optional(),
  latitude: z.number().optional(),
  longitude: z.number().optional(),
});

export const zAvalancheBulletinPhoto = zAbstractPersistentObject.and(
  z.object({
    id: z.string().nullish(),
    url: z.string().optional(),
    copyright: z.string().optional(),
    date: z.iso.date().optional(),
    microRegionId: z.string().optional(),
    locationName: z.string().optional(),
    latitude: z.number().optional(),
    longitude: z.number().optional(),
  }),
);

export const zAvalancheBulletinServiceLatestBulletin = z.object({
  date: z.iso.datetime(),
});

export const zAvalancheProblem1 = z.enum([
  "new_snow",
  "wind_slab",
  "persistent_weak_layers",
  "wet_snow",
  "gliding_snow",
  "favourable_situation",
  "cornices",
  "no_distinct_avalanche_problem",
]);

export const zAvalancheSize = z.enum(["small", "medium", "large", "very_large", "extreme"]);

export const zAvalancheType = z.enum(["slab", "loose", "glide"]);

export const zBlogItem = z.object({
  id: z.string(),
  title: z.string(),
  content: z.string(),
  published: z.iso.datetime(),
  categories: z.array(z.string()),
  attachmentUrl: z.string(),
});

export const zBulletinStatus = z.enum([
  "republished",
  "resubmitted",
  "updated",
  "published",
  "submitted",
  "draft",
  "missing",
]);

export const zAvalancheBulletinStatusServiceStatus = z.object({
  date: z.iso.datetime(),
  timestamp: z.iso.datetime(),
  status: zBulletinStatus,
  isBeingPublished: z.boolean(),
});

/**
 * The version of CAAML (Canadian Avalanche Association Markup Language)
 */
export const zCaamlVersion = z.enum(["V6", "V6_JSON"]);

export const zCharacteristic = z.enum(["low", "medium", "high", "very_high"]);

export const zComplexity = z.enum(["easy", "challenging", "complex"]);

export const zCreationProcess = z.enum([
  "radiation_recrystallization",
  "diurnal_recrystallization",
  "melt_layer_recrystallization",
  "surface_hoar_formation",
]);

export const zCrust = z.enum(["no", "partly", "yes"]);

export const zDangerPattern = z.enum(["dp1", "dp2", "dp3", "dp4", "dp5", "dp6", "dp7", "dp8", "dp9", "dp10"]);

export const zDangerRating = z.enum([
  "missing",
  "no_snow",
  "no_rating",
  "low",
  "moderate",
  "considerable",
  "high",
  "very_high",
]);

export const zAvalancheBulletinServiceHighest = z.object({
  dangerRating: zDangerRating,
});

export const zDangerRatingModificator = z.enum(["none", "minus", "equal", "plus"]);

export const zDangerSign = z.enum(["shooting_cracks", "whumpfing", "fresh_avalanches", "glide_cracks"]);

/**
 * This class holds all information about one danger source.
 */
export const zDangerSource = zAbstractPersistentObject.and(
  z.object({
    id: z.string().nullish(),
    ownerRegion: z.string().optional(),
    creationDate: z.iso.datetime().optional(),
    title: z.string().optional(),
    description: z.string().optional(),
  }),
);

export const zDangerSourceVariantStatus = z.enum(["active", "dormant", "inactive"]);

export const zDangerSourceVariantType = z.enum(["forecast", "analysis"]);

export const zDangerSourceVariantsStatus = z.object({
  date: z.iso.datetime(),
  forecast: z.boolean(),
  analysis: z.boolean(),
});

export const zDaytime = z.enum([
  "evening",
  "first_night_half",
  "second_night_half",
  "morning",
  "forenoon",
  "afternoon",
]);

export const zDirection = z.enum(["up", "down"]);

export const zDistribution = z.enum(["isolated", "specific", "widespread"]);

export const zFrequency = z.enum(["none", "few", "some", "many"]);

export const zGenericObservationImportantObservation = z.enum([
  "SnowLine",
  "SurfaceHoar",
  "Graupel",
  "StabilityTest",
  "IceFormation",
  "VeryLightNewSnow",
  "ForBlog",
]);

export const zGenericObservationObservationType = z.enum([
  "SimpleObservation",
  "Evaluation",
  "Avalanche",
  "Blasting",
  "Closure",
  "Profile",
  "TimeSeries",
  "Webcam",
  "DrySnowfallLevel",
]);

export const zGenericObservationPersonInvolvement = z.enum(["Dead", "Injured", "Uninjured", "No", "Unknown"]);

export const zGenericObservation = z.object({
  $source: z.string(),
  $id: z.string(),
  $type: zGenericObservationObservationType,
  $externalURL: z.string().optional(),
  stability: z.string().optional(),
  aspects: z.array(zAspect).optional(),
  authorName: z.string().optional(),
  content: z.string().optional(),
  $data: z.record(z.string(), z.unknown()).optional(),
  elevation: z
    .int()
    .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" })
    .optional(),
  elevationLowerBound: z
    .int()
    .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" })
    .optional(),
  elevationUpperBound: z
    .int()
    .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" })
    .optional(),
  eventDate: z.iso.datetime().optional(),
  latitude: z.number().optional(),
  locationName: z.string().optional(),
  longitude: z.number().optional(),
  region: z.string().optional(),
  reportDate: z.iso.datetime().optional(),
  avalancheProblems: z.array(zAvalancheProblem1).optional(),
  dangerPatterns: z.array(zDangerPattern).optional(),
  importantObservation: z.array(zGenericObservationImportantObservation).optional(),
  extraDialogRows: z.record(z.string(), z.unknown()).optional(),
  $externalImgs: z.string().optional(),
  personInvolvement: zGenericObservationPersonInvolvement.optional(),
  $deleted: z.boolean().optional(),
  allowEdit: z.boolean().optional(),
  dangerSource: zDangerSource.nullish(),
});

export const zGlidingSnowActivity = z.enum(["low", "medium", "high"]);

export const zGrainShape = z.enum([
  "PP",
  "MM",
  "DF",
  "RG",
  "FC",
  "DH",
  "SH",
  "MF",
  "IF",
  "PPco",
  "PPnd",
  "PPpl",
  "PPsd",
  "PPir",
  "PPgp",
  "PPhl",
  "PPip",
  "PPrm",
  "MMrp",
  "MMci",
  "DFdc",
  "DFbk",
  "RGsr",
  "RGlr",
  "RGwp",
  "RGxf",
  "FCso",
  "FCsf",
  "FCxr",
  "DHcp",
  "DHpr",
  "DHch",
  "DHla",
  "DHxr",
  "SHsu",
  "SHcv",
  "SHxr",
  "MFcl",
  "MFpc",
  "MFsl",
  "MFcr",
  "IFil",
  "IFic",
  "IFbi",
  "IFrc",
  "IFsc",
]);

export const zHandHardness = z.enum(["fist", "four_fingers", "one_finger", "pencil", "knife", "ice"]);

export const zHazardSiteDistribution = z.enum(["single", "some", "many", "many_most", "moderately_steep"]);

export const zIncident = zAbstractPersistentObject.and(
  z.object({
    id: z.string().nullish(),
    createdAt: z.iso.datetime().optional(),
    updatedAt: z.iso.datetime().optional(),
    data: z.record(z.string(), z.unknown()).optional(),
    publishedAt: z.iso.datetime().optional(),
    publicData: z.record(z.string(), z.unknown()).optional(),
  }),
);

export const zIncidentAttachment = z.object({
  id: z.uuid(),
  dateAdded: z.iso.datetime(),
  fileName: z.string(),
  mediaType: z.string(),
  dateCreated: z.iso.datetime(),
  credit: z.string(),
  caption: z.string(),
  altText: z.string(),
  public: z.boolean(),
  attachmentCategory: z.string(),
  attachmentTags: z.array(z.string()),
});

/**
 * The enum contains the ISO 639-1 codes for available languages.
 */
export const zLanguageCode = z.enum(["de", "it", "en", "fr", "es", "ca", "oc"]);

export const zAvalancheBulletinText = z.object({
  languageCode: zLanguageCode,
  text: z.string(),
});

export const zLocalServerInstance = z.object({
  publishAt5PM: z.boolean(),
  publishAt8AM: z.boolean(),
  mapsPath: z.string(),
  mapProductionUrl: z.string(),
  pdfDirectory: z.string(),
  htmlDirectory: z.string(),
  mediaPath: z.string(),
});

export const zNaturalAvalancheReleaseProbability = z.enum(["one", "two", "three", "four"]);

export const zMatrixInformation = z.object({
  artificialDangerRating: zDangerRating.optional(),
  artificialAvalancheSize: zAvalancheSize.optional(),
  artificialAvalancheReleaseProbability: zArtificialAvalancheReleaseProbability.optional(),
  artificialHazardSiteDistribution: zHazardSiteDistribution.optional(),
  naturalDangerRating: zDangerRating.optional(),
  naturalAvalancheReleaseProbability: zNaturalAvalancheReleaseProbability.optional(),
  naturalHazardSiteDistribution: zHazardSiteDistribution.optional(),
});

export const zPosition = z.enum(["topleft", "topright", "bottomleft", "bottomright"]);

export const zProbability = z.enum(["likely", "possible", "unlikely"]);

export const zPublicationChecklistItem = zAbstractPersistentObject.and(
  z.object({
    id: z.string().nullish(),
    publicationChannel: z.string().optional(),
    ok: z.boolean().optional(),
    problemDescription: z.string().optional(),
  }),
);

export const zChecklistServiceChecklist = z.object({
  checklistId: z.string(),
  timestamp: z.iso.datetime(),
  checklistItems: z.array(zPublicationChecklistItem),
  user: z.string(),
});

export const zPublicationStrategyType = z.enum(["publish", "noMessages", "minimalCAAML"]);

export const zPushSubscription = z.object({
  id: z.coerce
    .bigint()
    .min(BigInt("-9223372036854775808"), { error: "Invalid value: Expected int64 to be >= -9223372036854775808" })
    .max(BigInt("9223372036854775807"), { error: "Invalid value: Expected int64 to be <= 9223372036854775807" })
    .nullish(),
  subscribeDate: z.iso.datetime().optional(),
  auth: z.string().optional(),
  p256dh: z.string().optional(),
  endpoint: z.string().optional(),
  language: zLanguageCode.optional(),
  region: z.string().optional(),
  failedCount: z
    .int()
    .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" })
    .optional(),
});

export const zRecognizability = z.enum(["very_easy", "easy", "hard", "very_hard"]);

export const zRegionLanguageConfiguration = z.object({
  lang: zLanguageCode.optional(),
  websiteName: z.string().optional(),
  warningServiceName: z.string().optional(),
  warningServiceEmail: z.string().optional(),
  url: z.string().optional(),
  urlWithDate: z.string().optional(),
});

export const zRole = z.enum(["SUPERADMIN", "ADMIN", "FORECASTER", "FOREMAN", "OBSERVER"]);

/**
 * This class holds all information about a server instance.
 */
export const zServerInstance = z.object({
  id: z.coerce
    .bigint()
    .min(BigInt("-9223372036854775808"), { error: "Invalid value: Expected int64 to be >= -9223372036854775808" })
    .max(BigInt("9223372036854775807"), { error: "Invalid value: Expected int64 to be <= 9223372036854775807" })
    .nullish(),
  name: z.string().optional(),
  apiUrl: z.string().optional(),
  userName: z.string().optional(),
  password: z.string().optional(),
  externalServer: z.boolean().optional(),
});

export const zServerInstanceServiceServerVersionInfo = z.object({
  version: z.string(),
});

export const zSlopeGradient = z.enum(["moderately_steep", "steep", "very_steep", "extremely_steep"]);

export const zSnowpackPosition = z.enum(["upper", "middle", "lower", "ground"]);

export const zSnowpackStability = z.enum(["good", "fair", "poor", "very_poor"]);

export const zEawsMatrixInformation = z.object({
  dangerRating: zDangerRating.optional(),
  dangerRatingModificator: zDangerRatingModificator.optional(),
  avalancheSize: zAvalancheSize.optional(),
  snowpackStability: zSnowpackStability.optional(),
  frequency: zFrequency.optional(),
  avalancheSizeValue: z
    .int()
    .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" })
    .optional(),
  snowpackStabilityValue: z
    .int()
    .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" })
    .optional(),
  frequencyValue: z
    .int()
    .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" })
    .optional(),
});

export const zAvalancheProblem = zAbstractPersistentObject.and(
  z.object({
    id: z.string().nullish(),
    avalancheType: zAvalancheType.optional(),
    avalancheProblem: zAvalancheProblem1.optional(),
    aspects: z.array(zAspect).optional(),
    elevationHigh: z
      .int()
      .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
      .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" })
      .optional(),
    treelineHigh: z.boolean().optional(),
    elevationLow: z
      .int()
      .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
      .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" })
      .optional(),
    treelineLow: z.boolean().optional(),
    dangerRatingDirection: zDirection.optional(),
    matrixInformation: zMatrixInformation.optional(),
    eawsMatrixInformation: zEawsMatrixInformation.optional(),
  }),
);

export const zAvalancheBulletinDaytimeDescription = zAbstractPersistentObject.and(
  z.object({
    id: z.string().nullish(),
    warningLevelId: z.string().optional(),
    hasElevationDependency: z.boolean().optional(),
    elevation: z
      .int()
      .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
      .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" })
      .optional(),
    treeline: z.boolean().optional(),
    dangerRatingAbove: zDangerRating.optional(),
    dangerRatingBelow: zDangerRating.optional(),
    complexity: zComplexity.optional(),
    avalancheProblem1: zAvalancheProblem.nullish(),
    avalancheProblem2: zAvalancheProblem.nullish(),
    avalancheProblem3: zAvalancheProblem.nullish(),
    avalancheProblem4: zAvalancheProblem.nullish(),
    avalancheProblem5: zAvalancheProblem.nullish(),
  }),
);

export const zStatusInformation = z.object({
  ok: z.boolean(),
  title: z.string(),
  message: z.string(),
});

export const zStrategicMindset = z.enum([
  "assessment",
  "stepping_out",
  "status_quo",
  "stepping_back",
  "entrenchment",
  "free_ride",
  "high_alert",
  "spring_diurnal",
]);

export const zStressLevel = z.object({
  date: z.iso.date().optional(),
  stressLevel: z
    .int()
    .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" })
    .optional(),
  lastUpdated: z.iso.datetime().optional(),
});

export const zSubscriptionServiceEmailSubscription = z.object({
  email: z.string(),
  regions: z.string(),
  language: zLanguageCode,
});

export const zTendency = z.enum(["decreasing", "steady", "increasing"]);

export const zTerrainType = z.enum([
  "gullies_and_bowls",
  "adjacent_to_ridgelines",
  "distant_from_ridgelines",
  "in_the_vicinity_of_peaks",
  "pass_areas",
  "shady_slopes",
  "sunny_slopes",
  "grassy_slopes",
  "cut_slopes",
  "wind_loaded_slopes",
  "base_of_rock_walls",
  "behind_abrupt_changes_in_the_terrain",
  "transitions_into_gullies_and_bowls",
  "areas_where_the_snow_cover_is_rather_shallow",
  "transitions_from_a_shallow_to_a_deep_snowpack",
  "highly_frequented_off_piste_terrain",
  "little_used_backcountry_terrain",
  "places_that_are_protected_from_the_wind",
  "regions_exposed_to_the_foehn_wind",
  "regions_with_a_lot_of_snow",
  "regions_exposed_to_precipitation",
  "regions_exposed_to_heavier_precipitation",
]);

export const zTextPart = z.enum([
  "generalHeadlineComment",
  "highlights",
  "avActivityHighlights",
  "avActivityComment",
  "snowpackStructureHighlights",
  "snowpackStructureComment",
  "synopsisHighlights",
  "synopsisComment",
  "tendencyComment",
  "travelAdvisoryHighlights",
  "travelAdvisoryComment",
]);

/**
 * This class holds all information about one region.
 */
export const zRegion = z.object({
  id: z.string().optional(),
  microRegions: z
    .int()
    .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" })
    .optional(),
  subRegions: z.array(z.string()).optional(),
  superRegions: z.array(z.string()).optional(),
  neighborRegions: z.array(z.string()).optional(),
  languageConfigurations: z.array(zRegionLanguageConfiguration).optional(),
  staticUrl: z.string().optional(),
  enabledLanguages: z.array(zLanguageCode).optional(),
  ttsLanguages: z.array(zLanguageCode).optional(),
  publishBulletins: z.boolean().optional(),
  publishBlogs: z.boolean().optional(),
  createCaamlV6: z.boolean().optional(),
  createJson: z.boolean().optional(),
  createMaps: z.boolean().optional(),
  createPdf: z.boolean().optional(),
  createSimpleHtml: z.boolean().optional(),
  sendEmails: z.boolean().optional(),
  sendTelegramMessages: z.boolean().optional(),
  sendWhatsAppMessages: z.boolean().optional(),
  sendPushNotifications: z.boolean().optional(),
  enableMediaFile: z.boolean().optional(),
  enableIcon: z.boolean().optional(),
  enableAvalancheProblemCornices: z.boolean().optional(),
  enableAvalancheProblemNoDistinctAvalancheProblem: z.boolean().optional(),
  showMatrix: z.boolean().optional(),
  enableStrategicMindset: z.boolean().optional(),
  enableStressLevel: z.boolean().optional(),
  pdfColor: z.string().optional(),
  emailColor: z.string().optional(),
  pdfMapYAmPm: z
    .int()
    .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" })
    .optional(),
  pdfMapYFd: z
    .int()
    .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" })
    .optional(),
  pdfMapWidthAmPm: z
    .int()
    .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" })
    .optional(),
  pdfMapWidthFd: z
    .int()
    .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" })
    .optional(),
  pdfMapHeight: z
    .int()
    .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" })
    .optional(),
  pdfFooterLogo: z.boolean().optional(),
  pdfFooterLogoColorPath: z.string().optional(),
  pdfFooterLogoBwPath: z.string().optional(),
  geoDataDirectory: z.string().optional(),
  mapLogoPosition: zPosition.optional(),
  imageColorbarColorPath: z.string().optional(),
  imageColorbarBwPath: z.string().optional(),
  enableDangerSources: z.boolean().optional(),
  enableObservations: z.boolean().optional(),
  enableIncidents: z.boolean().optional(),
  enableModelling: z.boolean().optional(),
  enabledTextcatFields: z.array(zTextPart).optional(),
  enabledEditableFields: z.array(zTextPart).optional(),
  enableLineaExport: z.boolean().optional(),
  defaultLang: zLanguageCode.optional(),
  logoPath: z.string().optional(),
  logoBwPath: z.string().optional(),
  coatOfArms: z.string().optional(),
  serverImagesUrl: z.string().optional(),
  educationUrl: z.string().optional(),
  awsomeUrl: z.string().optional(),
});

export const zThickness = z.enum(["thick", "thin"]);

export const zUser = z.object({
  email: z.string().optional(),
  password: z.string().optional(),
  name: z.string().optional(),
  roles: z.array(zRole).optional(),
  regions: z.array(z.string()).optional(),
  image: z.string().optional(),
  organization: z.string().optional(),
  languageCode: zLanguageCode.optional(),
  deleted: z.boolean().optional(),
});

export const zAuthenticationServiceAuthenticationResponse = z.object({
  user: zUser,
  regions: z.array(zRegion),
  access_token: z.string(),
});

/**
 * This class holds all information about one avalanche bulletin.
 */
export const zAvalancheBulletin = zAbstractPersistentObject.and(
  z.object({
    id: z.string().nullish(),
    author: zUser.nullish(),
    additionalAuthors: z.array(z.string()).optional(),
    updateDate: z.iso.datetime().optional(),
    ownerRegion: z.string().optional(),
    highlightsTextcat: z.string().optional(),
    avActivityHighlightsTextcat: z.string().optional(),
    avActivityCommentTextcat: z.string().optional(),
    snowpackStructureHighlightsTextcat: z.string().optional(),
    snowpackStructureCommentTextcat: z.string().optional(),
    tendencyCommentTextcat: z.string().optional(),
    generalHeadlineCommentTextcat: z.string().optional(),
    synopsisCommentTextcat: z.string().optional(),
    avActivityHighlightsNotes: z.string().optional(),
    avActivityCommentNotes: z.string().optional(),
    snowpackStructureHighlightsNotes: z.string().optional(),
    snowpackStructureCommentNotes: z.string().optional(),
    tendencyCommentNotes: z.string().optional(),
    generalHeadlineCommentNotes: z.string().optional(),
    highlights: z.array(zAvalancheBulletinText).optional(),
    avActivityHighlights: z.array(zAvalancheBulletinText).optional(),
    avActivityComment: z.array(zAvalancheBulletinText).optional(),
    synopsisHighlights: z.array(zAvalancheBulletinText).optional(),
    synopsisComment: z.array(zAvalancheBulletinText).optional(),
    snowpackStructureHighlights: z.array(zAvalancheBulletinText).optional(),
    snowpackStructureComment: z.array(zAvalancheBulletinText).optional(),
    travelAdvisoryHighlights: z.array(zAvalancheBulletinText).optional(),
    travelAdvisoryComment: z.array(zAvalancheBulletinText).optional(),
    tendencyComment: z.array(zAvalancheBulletinText).optional(),
    generalHeadlineComment: z.array(zAvalancheBulletinText).optional(),
    tendency: zTendency.optional(),
    dangerPattern1: zDangerPattern.optional(),
    dangerPattern2: zDangerPattern.optional(),
    publicationDate: z.iso.datetime().optional(),
    validity: zAvalancheBulletinValidity.optional(),
    suggestedRegions: z.array(z.string()).optional(),
    savedRegions: z.array(z.string()).optional(),
    savedOrPublishedRegions: z.array(z.string()).optional(),
    regions: z.array(z.string()).optional(),
    publishedRegions: z.array(z.string()).optional(),
    strategicMindset: zStrategicMindset.optional(),
    forenoon: zAvalancheBulletinDaytimeDescription.nullish(),
    afternoon: zAvalancheBulletinDaytimeDescription.nullish(),
    photos: z.array(zAvalancheBulletinPhoto).optional(),
    hasDaytimeDependency: z.boolean().optional(),
  }),
);

export const zUserServiceChangePassword = z.object({
  oldPassword: z.string(),
  newPassword: z.string(),
});

export const zUserServiceCheckPassword = z.object({
  password: z.string(),
});

export const zUserServiceResetPassword = z.object({
  newPassword: z.string(),
});

export const zWetness = z.enum(["wet", "moist", "dry"]);

/**
 * This class holds all information about one danger source variant.
 */
export const zDangerSourceVariant = zAbstractPersistentObject.and(
  z.object({
    id: z.string().nullish(),
    originalDangerSourceVariantId: z.string().optional(),
    forecastDangerSourceVariantId: z.string().optional(),
    dangerSource: zDangerSource.nullish(),
    title: z.string().optional(),
    creationDate: z.iso.datetime().optional(),
    updateDate: z.iso.datetime().optional(),
    validFrom: z.iso.datetime().optional(),
    validUntil: z.iso.datetime().optional(),
    dangerSourceVariantStatus: zDangerSourceVariantStatus.optional(),
    dangerSourceVariantType: zDangerSourceVariantType.optional(),
    ownerRegion: z.string().optional(),
    regions: z.array(z.string()).optional(),
    hasDaytimeDependency: z.boolean().optional(),
    avalancheType: zAvalancheType.optional(),
    aspects: z.array(zAspect).optional(),
    elevationHigh: z
      .int()
      .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
      .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" })
      .optional(),
    treelineHigh: z.boolean().optional(),
    elevationLow: z
      .int()
      .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
      .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" })
      .optional(),
    treelineLow: z.boolean().optional(),
    aspectsOfExistence: z.array(zAspect).optional(),
    elevationHighOfExistence: z
      .int()
      .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
      .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" })
      .optional(),
    treelineHighOfExistence: z.boolean().optional(),
    elevationLowOfExistence: z
      .int()
      .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
      .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" })
      .optional(),
    treelineLowOfExistence: z.boolean().optional(),
    dangerIncreaseWithElevation: z.boolean().optional(),
    highestDangerAspect: zAspect.optional(),
    dangerPeak: zDaytime.optional(),
    slopeGradient: zSlopeGradient.optional(),
    runoutIntoGreen: z.boolean().optional(),
    penetrateDeepLayers: z.boolean().optional(),
    naturalRelease: zProbability.optional(),
    dangerSigns: z.array(zDangerSign).optional(),
    eawsMatrixInformation: zEawsMatrixInformation.optional(),
    comment: z.string().optional(),
    textcat: z.string().optional(),
    uncertainty: z.string().optional(),
    glidingSnowActivity: zGlidingSnowActivity.optional(),
    glidingSnowActivityValue: z
      .int()
      .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
      .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" })
      .optional(),
    snowHeightUpperLimit: z
      .int()
      .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
      .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" })
      .optional(),
    snowHeightLowerLimit: z
      .int()
      .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
      .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" })
      .optional(),
    snowHeightAverage: z
      .int()
      .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
      .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" })
      .optional(),
    zeroDegreeIsotherm: z.boolean().optional(),
    slabGrainShape: zGrainShape.optional(),
    slabThicknessUpperLimit: z
      .int()
      .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
      .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" })
      .optional(),
    slabThicknessLowerLimit: z
      .int()
      .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
      .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" })
      .optional(),
    slabHandHardnessUpperLimit: zHandHardness.optional(),
    slabHandHardnessLowerLimit: zHandHardness.optional(),
    slabHardnessProfile: zTendency.optional(),
    slabEnergyTransferPotential: zCharacteristic.optional(),
    slabDistribution: zDistribution.optional(),
    weakLayerGrainShapes: z.array(zGrainShape).optional(),
    weakLayerGrainSizeUpperLimit: z.number().optional(),
    weakLayerGrainSizeLowerLimit: z.number().optional(),
    weakLayerPersistent: z.boolean().optional(),
    weakLayerThickness: zThickness.optional(),
    weakLayerStrength: zCharacteristic.optional(),
    weakLayerWet: z.boolean().optional(),
    weakLayerCrustAbove: zCrust.optional(),
    weakLayerCrustBelow: zCrust.optional(),
    weakLayerPosition: zSnowpackPosition.optional(),
    weakLayerCreation: zCreationProcess.optional(),
    weakLayerDistribution: zDistribution.optional(),
    dangerSpotRecognizability: zRecognizability.optional(),
    remoteTriggering: zProbability.optional(),
    terrainTypes: z.array(zTerrainType).optional(),
    looseSnowGrainShape: zGrainShape.optional(),
    looseSnowMoisture: zWetness.optional(),
  }),
);

/**
 * index 200 response
 */
export const zIndexResponse = z.string();

export const zLoginBody = zAuthenticationServiceCredentials;

/**
 * login 200 response
 */
export const zLoginResponse = zAuthenticationServiceAuthenticationResponse;

/**
 * testAuth 200 response
 */
export const zTestAuthResponse = zAuthenticationServiceUsername;

export const zGetBlogPostQuery = z.object({
  region: z.string().optional().default("AT-07"),
  lang: zLanguageCode.optional(),
  id: z.string(),
});

/**
 * getBlogPost 200 response
 */
export const zGetBlogPostResponse = zBlogItem;

export const zGetBlogPostsQuery = z.object({
  region: z.string().optional().default("AT-07"),
  lang: zLanguageCode.optional(),
  searchText: z.string(),
  searchCategory: z.string(),
  startDate: z.string(),
  endDate: z.string(),
});

/**
 * getBlogPosts 200 response
 */
export const zGetBlogPostsResponse = z.array(zBlogItem);

export const zSendLatestBlogPostQuery = z.object({
  region: z.string(),
  lang: zLanguageCode,
});

export const zSendLatestBlogPostEmailQuery = z.object({
  region: z.string(),
  lang: zLanguageCode,
});

export const zSendLatestBlogPostPushQuery = z.object({
  region: z.string(),
  lang: zLanguageCode,
});

export const zSendLatestBlogPostTelegramQuery = z.object({
  region: z.string(),
  lang: zLanguageCode,
});

export const zSendLatestBlogPostWhatsAppQuery = z.object({
  region: z.string(),
  lang: zLanguageCode,
});

export const zGetPublishedJsonBulletins0Query = z.object({
  version: zCaamlVersion.optional(),
  regions: z.array(z.string()),
  region: z.string(),
  date: z.string(),
  lang: zLanguageCode,
});

/**
 * bulletins
 */
export const zGetPublishedJsonBulletins0Response = z.array(zAvalancheBulletin);

export const zCreateJsonBulletinsBody = z.array(zAvalancheBulletin);

export const zCreateJsonBulletinsQuery = z.object({
  date: z.string(),
  region: z.string(),
});

/**
 * createJSONBulletins 200 response
 */
export const zCreateJsonBulletinsResponse = z.array(zAvalancheBulletin);

export const zCreateJsonBulletinBody = zAvalancheBulletin;

export const zCreateJsonBulletinQuery = z.object({
  date: z.string(),
  region: z.string(),
});

/**
 * createJSONBulletin 200 response
 */
export const zCreateJsonBulletinResponse = z.array(zAvalancheBulletin);

export const zGetPublishedCaamlBulletinsQuery = z.object({
  date: z.string(),
  regions: z.array(z.string()),
  lang: zLanguageCode,
  version: zCaamlVersion.optional(),
});

/**
 * getPublishedCaamlBulletins 200 response
 */
export const zGetPublishedCaamlBulletinsResponse = z.string();

export const zGetPublishedCaamlJsonBulletinsQuery = z.object({
  date: z.string(),
  regions: z.array(z.string()),
  lang: zLanguageCode,
  version: zCaamlVersion.optional(),
});

/**
 * getPublishedCaamlJsonBulletins 200 response
 */
export const zGetPublishedCaamlJsonBulletinsResponse = z.string();

export const zCheckBulletinsQuery = z.object({
  region: z.string(),
  date: z.string(),
});

/**
 * checkBulletins 200 response
 */
export const zCheckBulletinsResponse = z.array(z.string());

export const zGetJsonBulletinsQuery = z.object({
  date: z.string(),
  regions: z.array(z.string()),
});

/**
 * bulletins
 */
export const zGetJsonBulletinsResponse = z.array(zAvalancheBulletin);

export const zGetCaamlJsonBulletinsQuery = z.object({
  date: z.string(),
  regions: z.array(z.string()),
  lang: zLanguageCode,
  version: zCaamlVersion.optional(),
});

/**
 * getCaamlJsonBulletins 200 response
 */
export const zGetCaamlJsonBulletinsResponse = z.string();

export const zGetHighestDangerRatingQuery = z.object({
  date: z.string(),
  regions: z.array(z.string()),
});

/**
 * latest
 */
export const zGetHighestDangerRatingResponse = zAvalancheBulletinServiceHighest;

export const zGetPublishedJsonBulletinsQuery = z.object({
  date: z.string(),
  regions: z.array(z.string()),
  lang: zLanguageCode,
});

/**
 * bulletins
 */
export const zGetPublishedJsonBulletinsResponse = z.array(zAvalancheBulletin);

/**
 * getLatest 200 response
 */
export const zGetLatestResponse = zAvalancheBulletinServiceLatestBulletin;

export const zGetPublishedBulletinsAsPdfQuery = z.object({
  date: z.string(),
  bulletinId: z.string().nullish(),
  microRegionId: z.string().nullish(),
  region: z.string(),
  grayscale: z.boolean(),
  lang: zLanguageCode,
});

/**
 * getPublishedBulletinsAsPDF 200 response
 */
export const zGetPublishedBulletinsAsPdfResponse = z.string();

export const zUploadBulletinPhotoBody = z.object({
  file: z.string().optional(),
});

export const zUploadBulletinPhotoQuery = z.object({
  region: z.string(),
});

/**
 * uploadBulletinPhoto 200 response
 */
export const zUploadBulletinPhotoResponse = zAvalancheBulletinCustomDataBulletinPhoto;

export const zGetPreviewPdfBody = z.array(zAvalancheBulletin);

export const zGetPreviewPdfQuery = z.object({
  region: z.string(),
  lang: zLanguageCode,
});

/**
 * getPreviewPdf 200 response
 */
export const zGetPreviewPdfResponse = z.string();

export const zPublishBulletinsQuery = z.object({
  region: z.string(),
  strategy: zPublicationStrategyType.optional(),
  date: z.string(),
});

export const zPublishAllBulletinsQuery = z.object({
  date: z.string(),
  strategy: zPublicationStrategyType.optional(),
});

export const zSendEmailQuery = z.object({
  region: z.string(),
  date: z.string(),
  lang: zLanguageCode.nullish(),
});

export const zTriggerPushNotificationsQuery = z.object({
  region: z.string(),
  date: z.string(),
  lang: zLanguageCode.nullish(),
});

export const zTriggerTelegramChannelQuery = z.object({
  region: z.string(),
  date: z.string(),
  lang: zLanguageCode.nullish(),
});

export const zTriggerWhatsAppChannelQuery = z.object({
  region: z.string(),
  date: z.string(),
  lang: zLanguageCode.nullish(),
});

export const zGetStatusQuery = z.object({
  region: z.string(),
  timezone: z.string(),
  startDate: z.string(),
  endDate: z.string(),
});

/**
 * getStatus 200 response
 */
export const zGetStatusResponse = z.array(zAvalancheBulletinStatusServiceStatus);

export const zGetInternalStatusQuery = z.object({
  region: z.string(),
  startDate: z.string(),
  endDate: z.string(),
});

/**
 * getInternalStatus 200 response
 */
export const zGetInternalStatusResponse = z.array(zAvalancheBulletinStatusServiceStatus);

export const zGetPublicationStatusQuery = z.object({
  region: z.string(),
  date: z.string(),
});

/**
 * getPublicationStatus 200 response
 */
export const zGetPublicationStatusResponse = zAvalancheBulletinStatusServiceStatus;

export const zSubmitBulletinsQuery = z.object({
  region: z.string(),
  date: z.string(),
});

export const zDeleteJsonBulletinPath = z.object({
  bulletinId: z.string(),
});

export const zDeleteJsonBulletinQuery = z.object({
  date: z.string(),
  region: z.string(),
});

/**
 * deleteJSONBulletin 200 response
 */
export const zDeleteJsonBulletinResponse = z.array(zAvalancheBulletin);

export const zGetJsonBulletinPath = z.object({
  bulletinId: z.string(),
});

/**
 * bulletin
 */
export const zGetJsonBulletinResponse = zAvalancheBulletin;

export const zUpdateJsonBulletinBody = zAvalancheBulletin;

export const zUpdateJsonBulletinPath = z.object({
  bulletinId: z.string(),
});

export const zUpdateJsonBulletinQuery = z.object({
  date: z.string(),
  region: z.string(),
});

/**
 * updateJSONBulletin 200 response
 */
export const zUpdateJsonBulletinResponse = z.array(zAvalancheBulletin);

export const zGetChecklistsQuery = z.object({
  date: z.string(),
  region: z.string(),
});

/**
 * getChecklists 200 response
 */
export const zGetChecklistsResponse = z.array(zChecklistServiceChecklist);

export const zSaveChecklistBody = zChecklistServiceChecklist;

export const zSaveChecklistQuery = z.object({
  date: z.string(),
  region: z.string(),
});

/**
 * saveChecklist 200 response
 */
export const zSaveChecklistResponse = zChecklistServiceChecklist;

export const zGetDangerSourcesQuery = z.object({
  date: z.string(),
  region: z.string(),
});

/**
 * danger-sources
 */
export const zGetDangerSourcesResponse = z.array(zDangerSource);

export const zSaveDangerSourceBody = zDangerSource;

/**
 * saveDangerSource 200 response
 */
export const zSaveDangerSourceResponse = zDangerSource;

export const zGetVariantsQuery = z.object({
  date: z.string(),
  region: z.string(),
});

/**
 * danger-sources
 */
export const zGetVariantsResponse = z.array(zDangerSourceVariant);

export const zGetInternalStatus1Query = z.object({
  region: z.string(),
  startDate: z.string(),
  endDate: z.string(),
});

/**
 * getInternalStatus_1 200 response
 */
export const zGetInternalStatus1Response = z.array(zDangerSourceVariantsStatus);

export const zSaveDangerSourceVariantBody = zDangerSourceVariant;

export const zSaveDangerSourceVariantQuery = z.object({
  date: z.string(),
  region: z.string(),
});

/**
 * saveDangerSourceVariant 200 response
 */
export const zSaveDangerSourceVariantResponse = zDangerSourceVariant;

export const zReplaceVariantsBody = z.array(zDangerSourceVariant);

export const zReplaceVariantsQuery = z.object({
  date: z.string(),
  region: z.string(),
});

/**
 * replaceVariants 200 response
 */
export const zReplaceVariantsResponse = z.array(zDangerSourceVariant);

export const zDeleteVariantPath = z.object({
  variantId: z.string(),
});

export const zDeleteVariantQuery = z.object({
  date: z.string(),
  region: z.string(),
});

/**
 * deleteVariant 200 response
 */
export const zDeleteVariantResponse = z.array(zDangerSourceVariant);

export const zGetVariantByIdPath = z.object({
  variantId: z.string(),
});

/**
 * variant
 */
export const zGetVariantByIdResponse = zDangerSourceVariant;

export const zGetVariantsForDangerSourcePath = z.object({
  dangerSourceId: z.string(),
});

export const zGetVariantsForDangerSourceQuery = z.object({
  date: z.string(),
  region: z.string(),
});

/**
 * danger-sources
 */
export const zGetVariantsForDangerSourceResponse = z.array(zDangerSourceVariant);

export const zAddSubscriberBody = zSubscriptionServiceEmailSubscription;

export const zGetIncidentsQuery = z.object({
  region: z.string(),
  seasonYear: z
    .int()
    .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
  startDate: z.string().nullish(),
  endDate: z.string().nullish(),
});

/**
 * getIncidents 200 response
 */
export const zGetIncidentsResponse = z.string();

export const zCreateIncidentBody = z.string();

export const zCreateIncidentQuery = z.object({
  region: z.string(),
});

/**
 * createIncident 200 response
 */
export const zCreateIncidentResponse = zIncident;

export const zDeleteIncidentPath = z.object({
  id: z.uuid(),
});

export const zGetIncidentPath = z.object({
  id: z.uuid(),
});

/**
 * getIncident 200 response
 */
export const zGetIncidentResponse = z.string();

export const zUpdateIncidentBody = z.string();

export const zUpdateIncidentPath = z.object({
  id: z.uuid(),
});

/**
 * updateIncident 200 response
 */
export const zUpdateIncidentResponse = zIncident;

export const zUploadIncidentAttachmentBody = z.object({
  file: z.string().optional(),
});

export const zUploadIncidentAttachmentPath = z.object({
  id: z.uuid(),
});

/**
 * uploadIncidentAttachment 200 response
 */
export const zUploadIncidentAttachmentResponse = zIncidentAttachment;

export const zDeleteIncidentAttachmentPath = z.object({
  id: z.uuid(),
  attachmentId: z.uuid(),
});

export const zGetIncidentAttachmentPath = z.object({
  id: z.uuid(),
  attachmentId: z.uuid(),
});

/**
 * getIncidentAttachment 200 response
 */
export const zGetIncidentAttachmentResponse = z.string();

export const zUnpublishIncidentPath = z.object({
  id: z.uuid(),
});

/**
 * unpublishIncident 200 response
 */
export const zUnpublishIncidentResponse = zIncident;

export const zPublishIncidentBody = z.string();

export const zPublishIncidentPath = z.object({
  id: z.uuid(),
});

/**
 * publishIncident 200 response
 */
export const zPublishIncidentResponse = zIncident;

export const zSaveMediaFileBody = z.object({
  text: z.string().optional(),
  file: z.string().optional(),
});

export const zSaveMediaFileQuery = z.object({
  date: z.string(),
  region: z.string(),
  lang: zLanguageCode,
  important: z.boolean(),
});

export const zGetRssFeedQuery = z.object({
  region: z.string().optional().default("AT-07"),
  lang: zLanguageCode.optional(),
});

/**
 * getRssFeed 200 response
 */
export const zGetRssFeedResponse = z.string();

export const zDeleteGenericObservationBody = zGenericObservation;

export const zGetGenericObservationsQuery = z.object({
  startDate: z.string(),
  endDate: z.string(),
});

/**
 * getGenericObservations 200 response
 */
export const zGetGenericObservationsResponse = z.array(zGenericObservation);

export const zSaveOrUpdateGenericObservationBody = zGenericObservation;

export const zGetGenericObservationQuery = z.object({
  source: z.string(),
  id: z.string(),
});

/**
 * getGenericObservation 200 response
 */
export const zGetGenericObservationResponse = zGenericObservation;

/**
 * getOpenApiJson 200 response
 */
export const zGetOpenApiJsonResponse = z.record(z.string(), z.unknown());

/**
 * getOpenApi 200 response
 */
export const zGetOpenApiResponse = z.string();

/**
 * key 200 response
 */
export const zKeyResponse = z.record(z.string(), z.unknown());

export const zSubscribeBody = zPushSubscription;

export const zUnsubscribeBody = zPushSubscription;

/**
 * getRegions 200 response
 */
export const zGetRegionsResponse = z.array(zRegion);

export const zSaveRegionBody = z.string();

/**
 * saveRegion 200 response
 */
export const zSaveRegionResponse = zRegion;

export const zGetRegionQuery = z.object({
  region: z.string(),
});

/**
 * getRegion 200 response
 */
export const zGetRegionResponse = zRegion;

/**
 * configuration
 */
export const zGetLocalServerConfigurationResponse = zLocalServerInstance;

export const zSaveServerConfigurationBody = zServerInstance;

/**
 * saveServerConfiguration 200 response
 */
export const zSaveServerConfigurationResponse = zServerInstance;

/**
 * configuration
 */
export const zGetExternalServerConfigurationsResponse = z.array(zServerInstance);

/**
 * server version info
 */
export const zGetServerVersionInfoResponse = zServerInstanceServiceServerVersionInfo;

export const zGetBulletinCsvQuery = z.object({
  startDate: z.string(),
  endDate: z.string(),
  lang: zLanguageCode,
  extended: z.boolean().optional().default(false),
  duplicate: z.boolean().optional().default(false),
  regions: z.array(z.string()),
  obsoleteMatrix: z.boolean().optional().default(false),
});

/**
 * getBulletinCsv 200 response
 */
export const zGetBulletinCsvResponse = z.string();

export const zGetDangerSourceCsvQuery = z.object({
  startDate: z.string(),
  endDate: z.string(),
});

/**
 * getDangerSourceCsv 200 response
 */
export const zGetDangerSourceCsvResponse = z.string();

export const zSaveVirtualRealityStatisticsBody = z.string();

/**
 * getStatus_1 200 response
 */
export const zGetStatus1Response = z.array(zStatusInformation);

/**
 * triggerStatusChecks 200 response
 */
export const zTriggerStatusChecksResponse = z.array(zStatusInformation);

/**
 * getUsers 200 response
 */
export const zGetUsersResponse = z.array(zUser);

export const zSaveUserBody = zUser;

/**
 * saveUser 200 response
 */
export const zSaveUserResponse = zUser;

export const zChangePasswordBody = zUserServiceChangePassword;

export const zCheckPasswordBody = zUserServiceCheckPassword;

/**
 * getRegions_1 200 response
 */
export const zGetRegions1Response = z.array(z.string());

/**
 * getRoles 200 response
 */
export const zGetRolesResponse = zRole;

export const zGetStressLevelsQuery = z.object({
  startDate: z.string(),
  endDate: z.string(),
});

/**
 * getStressLevels 200 response
 */
export const zGetStressLevelsResponse = z.array(zStressLevel);

export const zPostStressLevelBody = zStressLevel;

/**
 * postStressLevel 200 response
 */
export const zPostStressLevelResponse = zStressLevel;

export const zGetTeamStressLevelsQuery = z.object({
  region: z.string(),
  startDate: z.string(),
  endDate: z.string(),
});

/**
 * getTeamStressLevels 200 response
 */
export const zGetTeamStressLevelsResponse = z.record(z.string(), z.array(zStressLevel));

export const zDeleteUserPath = z.object({
  id: z.string(),
});

export const zResetPasswordBody = zUserServiceResetPassword;

export const zResetPasswordPath = z.object({
  id: z.string(),
});
