import { GenericObservation, ObservationSource, ObservationType } from ".";

// https://www.it-wms.com/en/wms_products/panocloud-panoramacamera/
// https://schoeneben4.it-wms.com/common/1.0/index.php?mod=loadMapData
export const webcams = {
  SUCCESS: true,
  CONFIG: {
    layers: {
      default: "OSM",
      list: [
        {
          name: "OSM",
          url: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
          config: {
            maxZoom: 17,
            attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors',
          },
          title: "OSM",
        },
        {
          name: "worldImage",
          url: "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
          config: {
            maxZoom: 17,
            attribution:
              "Tiles &copy; Esri &mdash; Source: Esri, i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community",
          },
          title: "ESRI World Image",
        },
      ],
    },
    map: {
      icon: "marker-7.png",
      coordinates: [46.80450439, 10.49105263],
      imageFilename: "/img/map/34eac3c5f470f603bbab1ae855a29f9a.png",
      imageHttp: "//schoeneben4.it-wms.com/img/map/34eac3c5f470f603bbab1ae855a29f9a.png",
      link: "http://www.schoeneben.it",
      title: "Sch\u00f6neben Bergstation",
      linkDescription: "mehr Information",
      MAP_TITLE: "Sch\u00f6neben Bergstation",
      MAP_LINK_DESCRIPTION: "more Info",
      MAP_HTTP: "http://www.schoeneben.it",
      defaultZoom: "12",
      radarColor: "#f29400",
      linkOpen: "_blank",
    },
    points: [
      {
        icon: "marker-7b.png",
        coordinates: [46.79541779, 10.49311256],
        imageFilename: null,
        imageHttp: "//schoeneben2.it-wms.com/tmb_panorama1.jpg",
        link: "//schoeneben2.it-wms.com",
        title: "Sch\u00f6neben",
        linkDescription: "Sch\u00f6neben",
        MAP_TITLE: "Sch\u00f6neben",
        MAP_LINK_DESCRIPTION: null,
        MAP_HTTP: null,
      },
      {
        icon: "marker-7b.png",
        coordinates: [46.82159805, 10.50891781],
        imageFilename: null,
        imageHttp: "//schoeneben3.it-wms.com/tmb_panorama1.jpg",
        link: "//schoeneben3.it-wms.com",
        title: "Talstation Sch\u00f6neben",
        linkDescription: "Talstation Sch\u00f6neben",
        MAP_TITLE: "Talstation Sch\u00f6neben",
        MAP_LINK_DESCRIPTION: null,
        MAP_HTTP: null,
      },
      {
        icon: "marker-7b.png",
        coordinates: [46.79394531, 10.48985863],
        imageFilename: null,
        imageHttp: "//schoeneben5.it-wms.com/tmb_panorama1.jpg",
        link: "//schoeneben5.it-wms.com",
        title: "Bergstation Rojensesselbahn",
        linkDescription: "Bergstation Rojensesselbahn",
        MAP_TITLE: "Mountain station Rojensesselbahn",
        MAP_LINK_DESCRIPTION: null,
        MAP_HTTP: null,
      },
      {
        icon: "marker-7b.png",
        coordinates: [46.8012352, 10.51065445],
        imageFilename: null,
        imageHttp: "//schoeneben6.it-wms.com/tmb_panorama1.jpg",
        link: "//schoeneben6.it-wms.com",
        title: "Zentralstation-H\u00f6llental",
        linkDescription: "Zentralstation-H\u00f6llental",
        MAP_TITLE: "Zentralstation-H\u00f6llental",
        MAP_LINK_DESCRIPTION: null,
        MAP_HTTP: null,
      },
      {
        icon: "marker-7b.png",
        coordinates: [46.8012352, 10.51065445],
        imageFilename: null,
        imageHttp: "//schoeneben7.it-wms.com/tmb_panorama1.jpg",
        link: "//schoeneben7.it-wms.com",
        title: "Sch\u00f6neben - Haideralm Bahn-Bergstation",
        linkDescription: "Sch\u00f6neben - Haideralm Bahn-Bergstation",
      },
      {
        icon: "marker-7b.png",
        coordinates: [46.75017929, 10.53647614],
        imageFilename: null,
        imageHttp: "//alpenrose-haidersee.panocloud.webcam/tmb_panorama1.jpg",
        link: "//alpenrose-haidersee.panocloud.webcam",
        title: "Hotel-Restaurant-Alpenrose am Haidersee",
        linkDescription: "Hotel-Restaurant-Alpenrose am Haidersee",
      },
      {
        icon: "marker-7b.png",
        coordinates: [46.76538849, 10.53292656],
        imageFilename: null,
        imageHttp: "//stvalentin.it-wms.com/tmb_panorama1.jpg",
        link: "//stvalentin.it-wms.com",
        title: "Aparthotel Mountain Living - Ausblick - Haider Alm, Haidersee, Ortlerblick",
        linkDescription: "Aparthotel Mountain Living - Ausblick - Haider Alm, Haidersee, Ortlerblick",
        MAP_TITLE: "Aparthotel Mountain Living - Ausblick - Haider Alm, Haidersee, Ortlerblick",
        MAP_LINK_DESCRIPTION: null,
        MAP_HTTP: null,
      },
      {
        icon: "marker-7b.png",
        coordinates: [46.76412964, 10.53199577],
        imageFilename: null,
        imageHttp: "//campingamsee.panocloud.webcam/tmb_panorama1.jpg",
        link: "//campingamsee.panocloud.webcam",
        title: "Camping zum See",
        linkDescription: "Camping zum See",
        MAP_TITLE: "Camping zum See",
        MAP_LINK_DESCRIPTION: null,
        MAP_HTTP: null,
      },
      {
        icon: "marker-7b.png",
        coordinates: [46.7670784, 10.53270721],
        imageFilename: null,
        imageHttp: "//lamm.it-wms.com/tmb_current1.jpg",
        link: "//lamm.it-wms.com",
        title: "Hotel Lamm - St. Valentin am Haidersee",
        linkDescription: "Hotel Lamm - St. Valentin am Haidersee",
        MAP_TITLE: "Hotel Lamm - St. Valentin am Haidersee",
        MAP_LINK_DESCRIPTION: null,
        MAP_HTTP: null,
      },
      {
        icon: "marker-7b.png",
        coordinates: [46.76376724, 10.53325939],
        imageFilename: null,
        imageHttp: "//ortlerspitz.it-wms.com/tmb_panorama1.jpg",
        link: "//ortlerspitz.it-wms.com",
        title: "Hotel Ortlerspitz",
        linkDescription: "Hotel Ortlerspitz",
      },
      {
        icon: "marker-7b.png",
        coordinates: [46.8287468, 10.51831627],
        imageFilename: null,
        imageHttp: "//seehotel.panocloud.webcam/tmb_panorama1.jpg",
        link: "//seehotel.panocloud.webcam",
        title: "Seehotel Panorama Relax - Reschen",
        linkDescription: "Seehotel Panorama Relax - Reschen",
        MAP_TITLE: "Seehotel Panorama Relax - Reschen",
        MAP_LINK_DESCRIPTION: null,
        MAP_HTTP: null,
      },
    ],
    showRadar: true,
    offsetDir: -160,
    mapOpenLink: "_self",
    showMapOnLoad: "hide",
  },
}.CONFIG.points;

export function convertPanoCloudWebcam(webcam: (typeof webcams)[number]): GenericObservation {
  return {
    $data: webcam,
    $externalURL: webcam.link,
    $source: ObservationSource.PanoCloud,
    $type: ObservationType.Webcam,
    authorName: "ras.bz.it",
    eventDate: new Date(),
    latitude: webcam.coordinates[0],
    longitude: webcam.coordinates[1],
    locationName: webcam.title,
  };
}
